### ISSUE TITLE
Where to "add some HTML code to your web page" using wordpress

### ISSUE THREAD

**Issue by teach4learning** [code4recovery/tsml-ui#104]
I'm volunteer managing Wordpress site for intergroup <cbiaa.org>. Meeting app already installed and working. Where do I add the recommended shortcode-- [tsml_react] ? I only have access to Wordpress dashboard, so no listing via there for a "web page" for "meetings." If I had access to server and looked at directory where Wordpress is installed, what specific file would I look for to "add the shortcode"?

Thanks in advance

**Comment by joshreisner** [comment]
Ah, this is a WordPress shortcode that you can use in your pages. Here's a link for more info: https://www.wpbeginner.com/wp-tutorials/how-to-add-a-shortcode-in-wordpress/

I've added some help text to the config tool to help future people with this question.

If you have any trouble with the shortcode then https://github.com/code4recovery/12-step-meeting-list/issues will be the right place to ask.
