### ISSUE TITLE
Lagging when opening meeting

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#108]
I've noticed there is lagging for a few seconds when opening a meeting from the list, as well as closing it to go back to the meeting list view. This does not happen with the WordPress plugin.

**Comment by joshreisner** [comment]
I'm not observing that on the example website, are you? https://react.meetingguide.org

If you're still experiencing that on your site please share a link to the TSML UI page and we can investigate.

**Comment by Grateful-Viv** [comment]
This only occurs when first bring up the page with the shortcode [tsml_react]

And then it only occurs when I press the back button on my browser (Chrome in Windows 10). If I open a meeting from the meeting list and press Back to Meetings, it is immediate.

I just tested on Firefox and it is even slower.

**Comment by joshreisner** [comment]
There's not much we can do about the initial load, but I think I may have fixed the reloading that was happening when the back button is clicked. 

Thanks, I hadn't noticed that was happening. I'm glad that seems to have been an easy fix.
