### ISSUE TITLE
Map for Virtual-Only meetings?

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#109]
Would it be possible to not display a map for virtual meetings? I see that aasfmarin.org has it blank.

Or have it default to something a graphic with headphones and video camera overlaid?

**Comment by joshreisner** [comment]
Yes, meetings that are not happening in person should not show a map. If you're still seeing maps on those meetings, please share a link so we can investigate.

If you wan to style the blank area for an online meeting you can use CSS to do that now. Here's some example CSS that you can customize to fit your needs: 

```
#tsml-ui .meeting.online .map::after {
  background-image: url(https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=1440&ixid=MnwxfDB8MXxhbGx8fHx8fHx8fHwxNjIyMTIzODkw&ixlib=rb-1.2.1&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1920);
  background-position: center center;
  background-repeat: no-repeat;
  background-size: cover;
  bottom: 0;
  content: '';
  left: 0;
  opacity: 0.25;
  position: absolute;
  right: 0;
  top: 0;
}
```

It should produce a result that looks like this:

![screenshot-online-meeting](https://user-images.githubusercontent.com/1551689/119998554-a84b6100-bf85-11eb-9b96-9ab1c7d62566.png)

**Comment by Grateful-Viv** [comment]
That's kind of awesome! I might even keep the graphic. :)

I see the color coding for meetings has been made such as pink x for inactive, blue for virtual, green for indoors, etc. 

I also noticed it's keeping count of active, in-person, online and hybrid which are not selectable types (currently). I'm going to assume it's figuring out hybrid because there's a URL AND the type is not TC. Meetings that are virtual only (and don't have TC as type) are added to the online mixture. So I can assume active is only counting TC types. Very well done, indeed.

There's some other suggestions, but I'm going to attempt to do what you asked for @joshreisner, and keep separate threads for each.

Thank you & excellent work.

Much appreciated.

**Comment by Grateful-Viv** [comment]
What would be the equivalent CSS to use right now in the plugin to display an image instead of map for online meetings?

**Comment by Grateful-Viv** [comment]
If I wanted to make an image to replace blank map for suspended meeting, what would I use instead of meeting.online ?

**Comment by joshreisner** [comment]
you can now use `.meeting.inactive`

**Comment by Grateful-Viv** [comment]
Can any of this be done with the plugin?

**Comment by joshreisner** [comment]
Not currently. When the next release comes out I believe maps will be disabled on meetings that aren't meeting in person.

**Comment by Grateful-Viv** [comment]
This suddenly is not displaying the image. I know it's there because the link brings up the image (https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b). I am eventually going to do my own, but in the meantime this is nice. Did something change on your end?

#tsml-ui .meeting.online .map::after {
background-image: url(https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=1440&ixid=MnwxfDB8MXxhbGx8fHx8fHx8fHwxNjIyMTIzODkw&ixlib=rb-1.2.1&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1920);
  background-position: center center;
  background-repeat: no-repeat;
  background-size: cover;
  bottom: 0;
  content: '';
  left: 0;
  opacity: 0.25;
  position: absolute;
  right: 0;
  top: 0;
}

**Comment by joshreisner** [comment]
That code still works for me on my development site.

**Comment by Grateful-Viv** [comment]
It's not working on mine.

Nor is it here: https://react.meetingguide.org/

What's the URL of the development site?

**Comment by joshreisner** [comment]
the current code we're recommending for this purpose is: 
```
#tsml-ui .meeting.online:not(.in-person) .map::after {
  background-image: url(https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=1440&ixid=MnwxfDB8MXxhbGx8fHx8fHx8fHwxNjIyMTIzODkw&ixlib=rb-1.2.1&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1920);
  background-position: center center;
  background-repeat: no-repeat;
  background-size: cover;
  bottom: 0;
  content: '';
  left: 0;
  opacity: 0.25;
  position: absolute;
  right: 0;
  top: 0;
}
```
demo: https://code4recovery.org/tsml-ui

**Comment by Grateful-Viv** [comment]
Thanks, @joshreisner 

That was what I needed `#tsml-ui .meeting.online:not(.in-person) .map::after {` instead of `#tsml-ui .meeting.online .map::after {`
