### ISSUE TITLE
Meeting Counts

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#112]
My database says there are 147 meetings.

The count on the meeting list view says there are 105 active meetings., 61 in-person, 46 online, 2 hybrid.

61+46+2 = 109.

Are the hybrid meetings counting in online category and the in-person category? That could eliminate two, but I am still then left with 107, not 105.

Or have I made a mistake somewhere?
![counts](https://user-images.githubusercontent.com/62247421/120003814-16068580-bfa4-11eb-995b-bcd2cc184be0.png)

**Comment by brianw-area24** [comment]
The math works out.

You have 61 In-person, which includes the 2 Hybrid, so 59 In-person only
Likewise, the 46 online includes the 2 Hybrid, so 44, Online only

59 In-person only
44 Online only
2 Hybrid
---------
105 Active Meetings

Brian W
