### ISSUE TITLE
Hybrid Meeting Missing From Dropdown

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#117]
I am no longer seeing hybrid meetings as a type to select from. Are you developing on the same one at the same time we're looking at it?

If so, I will wait.

But I appreciated hybrid being a selectable type to choose from.

**Comment by joshreisner** [comment]
We met as a group and decided that Hybrid wasn't a good filter option for people looking for meetings. We believe the primary use-cases are people looking for in-person or online meetings, and needing to know which in the list *are* hybrid.

TSML-UI handles this by showing differently-colored labels, one for the street address, and one for the online button. It's looking like the next version of TSML will use the word "Hybrid" in the results. But neither will have Hybrid as an option to filter by. 

It can always be added as a custom type.

https://github.com/code4recovery/tsml-ui#why-not-a-hybrid-filter
