### ISSUE TITLE
Location / Group

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#119]
This seems to be an issue only for online meetings, otherwise it is pulling from the location name.

When it's an online meeting, it's displaying the Group Name in the list view, and if there is no group entered in that field, then it's blank.

It should all pull from the location field. I am not sure why you would want the group, but that could come after the location if there is enough real estate.

In the plugin version, when it's an online meeting with TC type, the location showing in the list view has the location displayed and greyed out. 

In the plugin version, when it's an online meeting without TC, but doesn't have a street address, it still displays whatever was put in the location field.

In the TSML-UI version, when it's an online meeting with TC type, the location showing in the list view is blank.

In the TSML-UI version, when it's an online meeting without TC, but doesn't have a street address, though 
location is "Virtual Only", it's blank in list view.

See attached.
The plugin view shows 6 online meetings that are all displaying whatever was entered in the location field. 5 have street addresses greyed out, 1 shows "virtual-only". 

The UI view shows 7 online meetings that are displaying data from the Group Name field. It should be the location field. 
![Plugin-online-location](https://user-images.githubusercontent.com/62247421/120123706-69343000-c17e-11eb-9791-7a3e9f989c9e.png)
![TSML-online-location](https://user-images.githubusercontent.com/62247421/120123709-70f3d480-c17e-11eb-8181-34cef9e829f8.png)

**Comment by joshreisner** [comment]
This is an intentional change that I understand is also coming to TSML; meetings that meet in person show the Location name, meetings that do not show the Group name.

It was said to be confusing to have, in one example, a church name as the "Location" of an online meeting.

**Comment by Grateful-Viv** [comment]
>It was said to be confusing to have, in one example, a church name as the "Location" of an online meeting.
It wasn't confusing when it was greyed out.

Not every meeting is part of a group.  Not sure what value Location/Group has if it's an online meeting to show either nothing or group, if one is entered.

What about showing location name if it's a physical meeting, and putting "Virtual" if it's an online meeting? 

Is the TSML Plugin going to stay for a while? Will it be updated to look similar to the UI version?

**Comment by tech2serve** [comment]
> Not every meeting is part of a group. Not sure what value Location/Group has if it's an online meeting to show either nothing or group, if one is entered.
> 
IMO, it has to do with identification. 

> What about showing location name if it's a physical meeting, and putting "Virtual" if it's an online meeting?
> 
> Is the TSML Plugin going to stay for a while? Will it be updated to look similar to the UI version?

We are working to keep TSML and TSMLui in sync up to a point. Our long term plan is to replace the plugin’s front end with TSMLui, which will make all the front ends consistent.

**Comment by Grateful-Viv** [comment]
>IMO, it has to do with identification.
I'm not following what you mean by identification. 

And is it possible to show the location name if it's a physical meeting, and display "Virtual" if it's an online meeting?

**Comment by joshreisner** [comment]
You could create a group called Virtual in TSML for these meetings. 

But in those cases where an existing group is providing online meetings, users will want to know that.

**Comment by tech2serve** [comment]
Hey @Grateful-Viv—

A little background might be in order. Part of what we (the broad “we”) learned in this is that 7th Tradition contributions dropped off significantly with the pandemic, and online groups didn’t seem to pick up with like donations. 

In concert with GSO, we’ve worked to continue to encourage inter-groups, districts, etc., to continue affiliating online meetings with existing service structures (of which Groups are a key part).  

So in addition to what Josh said about an existing group, some areas will (and arguably should) form new groups for their local online meetings if those meetings are not already affiliated with a group.

**Comment by Grateful-Viv** [comment]
>You could create a group called Virtual in TSML for these meetings.

Could do that, but that requires a district.

I guess I'm reacting this way because it's already seemingly redundant information to display the Group name. When I created the meeting entries, in order to avoid weird permalinks like BigBook-1, BigBook-2, Daily-Reflections-3, etc., I purposely named each meeting beginning with the Group Name (if there was one) followed by what kind of meeting it was. 

**Examples**:
- Wake Up Call Living Sober
- Fenwick Island Open Discussion
- Open Arms Steps & Traditions
- Fellowship of the Incurables Tuesday Discussion

So it's repeating the group name in this area, if there is one, and doesn't add any value. Other entities may have set up their meetings differently, so seeing that a certain online meeting is associated with a group makes sense.

![Repeating Group Names](https://user-images.githubusercontent.com/62247421/120220119-42234000-c20a-11eb-81dd-9db6d6c3a134.png)

**Comment by Grateful-Viv** [comment]
> A little background might be in order. Part of what we (the broad “we”) learned in this is that 7th Tradition contributions dropped off significantly with the pandemic, and online groups didn’t seem to pick up with like donations.
> 
> In concert with GSO, we’ve worked to continue to encourage inter-groups, districts, etc., to continue affiliating online meetings with existing service structures (of which Groups are a key part).
> 
> So in addition to what Josh said about an existing group, some areas will (and arguably should) form new groups for their local online meetings if those meetings are not already affiliated with a group.

Couldn't agree more. And perhaps there are additional ways to do this.

**Comment by Grateful-Viv** [comment]
A.A. now lets online only groups register as a group, though the information is hard to find. Attached is the form that we have that can be returned by email, mail or fax (who faxes anymore?). They don't seem to require a GSR, but that perhaps is because they haven't figured out what district they belong to. And in that case, it's not clear how this group actually has a voice in the A.A. service structure. I suppose they are working on it.

[Online-Meeting-Form-ENG-FILL-IN.pdf](https://github.com/code4recovery/tsml-ui/files/6571520/Online-Meeting-Form-ENG-FILL-IN.pdf)


The normal registration form requires a brick 'n mortar location to register a group. See https://www.aa.org/assets/en_US/e_group.pdf
