### ISSUE TITLE
City/Neighborhood Label

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#120]
Formerly Region, it's now City/Neighborhood and that doesn't always translate well.

Maybe call it area/neighborhood instead? Or why not put it back to region and leave it up to each entity to define it?

Some of us live in small towns and some of us are in larger cities where we would define it by neighborhood (like in NYC where it could be Chelsea, Midtown, Upper West Side, etc.).

**Comment by joshreisner** [comment]
You're right, this was a quick fix for San Francisco but not as broadly applicable as "Region." It's been switched back now.

There will eventually be a way in TSML to pass configuration options to TSML UI, although that doesn't exist yet.

**Comment by joshreisner** [comment]
I have a [pull request open](https://github.com/code4recovery/12-step-meeting-list/pull/341) on TSML that will pass the column names used in the plugin to TSML-UI.

So TSML users will be able to change the Region heading to something else by adding this to their theme's functions.php:

```
$tsml_columns['region'] = 'Neighborhood';
```
