### ISSUE TITLE
Change Location Temporarily Closed text

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#121]
See https://github.com/code4recovery/12-step-meeting-list/issues/356

This would be same case for the UI version.

Some of our online meetings that used to meet at a physical location, are now going back inside AND keeping the online meeting at the same time. Not as a hybrid meeting, but rather two separate meetings. 

For the online instance, it seems to be confusing people to see the text "location temporarily closed" since it's only this instance of this meeting that is not meeting in person. The location is open for other meetings.

Perhaps it could be changed to "Not meeting in person", or "This meeting is not meeting in person" (And take out the temporarily word).

**Comment by joshreisner** [comment]
This issue is being tracked now at https://github.com/code4recovery/spec/issues/29

This project gets its type names from the spec, when those change this will change as well.
