### ISSUE TITLE
Add Group Email and website URL to meeting detail. 

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#122]
We use both these fields a lot for groups to communicate with attendees. See https://sussexaa.org/meetings/shore-serenity-at-lewes-beach/ for example. 

I've also made our staging site live (for now). See the same meeting. It could rain tonight and announcements are added by the group by 4PM if the beach meeting is called off.

https://sdi-staging.sussexaa.org/sdi-meetings/?meeting=shore-serenity-at-lewes-beach

Thank you.

**Comment by joshreisner** [comment]
Ok, these are added now 👍

**Comment by Grateful-Viv** [comment]
Thank you. 👍🏽
