### ISSUE TITLE
Change Title from a search

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#124]
If I do a search for all meetings that have string open arms (which is the name of one of our groups), it returns this in the title: Meetings with ‘open arms’. Can it be changed to "All Meetings with the word(s) ‘open arms’? See https://github.com/code4recovery/tsml-ui/issues/123 to change "Meetings" if it is any type to "All Meetings".

If I do a search for in-person meetings that have string open arms, it returns this in the title: In-person Meetings with ‘open arms’. Can it be changed to "In-person Meetings with with the word(s) ‘open arms’?

If I do a search for active meetings that have string wake up call, it returns this in the title: Active Meetings with ‘wake up call’. Can it be changed to "Active Meetings with the word(s) ‘wake up call’’?

**Comment by joshreisner** [comment]
This is something that you can customize. Since you're on WordPress, when the next version of TSML ships, it should be possible to have this wording by adding the following to a child theme functions.php:

```
$tsml_ui_config['strings']['en']['title']['search_with'] = 'with the word(s) %search%';
```

![Screen Shot 2021-06-07 at 7 53 43 AM](https://user-images.githubusercontent.com/1551689/121039277-cecb8200-c765-11eb-8088-c61456b74471.png)

**Comment by Grateful-Viv** [comment]
The next version of the TSML plugin will look same as the TSML UI? 

When is it expected to be released?

**Comment by joshreisner** [comment]
My understanding is it won't look exactly like TSML UI, but it will have the same metatypes at the top of the Any Type menu, eg In-Person, Active, etc.

I don't think there's a firm ETA on its release yet.
