### ISSUE TITLE
Closed Meeting / Open Meeting - Meeting Detail View 

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#130]
Would it be possible to put the following under meeting information?

Instead of Closed (which is subject to misinterpretation with our meetings being "closed" or "open" because of the pandemic, change it to Closed Meeting and state somewhere after the types are bulleted

Closed meetings are for A.A. members only, or for those who have a drinking problem and “have a desire to stop drinking.”

Instead of Open , change it to Open Meeting and state somewhere after the types are bulleted

Open meetings are available to anyone interested in Alcoholics Anonymous’ program of recovery from alcoholism. Non-alcoholics may attend open meetings as observers.

**Comment by joshreisner** [comment]
Ok, I've added these definitions now behind an info icon in the list of types. This approach won't take up space for users who understand what these types mean, and will scale better if more definitions are added.

Changing the type terminology is something that has to be done in the spec first.
