### ISSUE TITLE
Virtual Only Meetings Should Not be Tied Physical Location

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#133]
See https://github.com/code4recovery/12-step-meeting-list/issues/371. This is a similar issue in that virtual only meetings that never met at a brick and mortar are tied to the same location even though the only thing they have in common is that they have the same address because we needed to put county and state (or some approximate address).

In TSML UI, it doesn't list it as same location. Instead it lists all the meetings that are sharing the address, and this is a confusing display. 

Is there a way to separate this? If not, what about if it's virtual only, then not even displaying these other meetings?

See https://sdi-staging.sussexaa.org/sdi-meetings/?meeting=daily-reflections-tuesday

And then what gets weird is if I select from the detail another meeting such as https://sdi-staging.sussexaa.org/sdi-meetings/?meeting=we-are-not-saints, I don't see any of the other meetings at that "location". Same goes for all other ones that are not part of the Daily Reflections Online Group. This is not true in TSML WP version. In the case, it still says there are xx meetings at this location.

![UI Meeting Detail](https://user-images.githubusercontent.com/62247421/122126373-a1cf3d00-cdff-11eb-8933-a4dcd2b4a313.png)

![UI We are Not Saints Meeting Detail](https://user-images.githubusercontent.com/62247421/122126387-a7c51e00-cdff-11eb-9531-f1ef8bb0d638.png)

**Comment by joshreisner** [comment]
Ok, I'm hoping I've solved this now. In addition to the colorful icons, there is new logic:

* If the meeting meets in person, then other in-person meetings at the same location are listed in the location section
* If the meeting meets online *and* belongs to a group, then other online meetings from that group are listed in the group section

**Comment by Grateful-Viv** [comment]
Looks great. Thank you.
