### ISSUE TITLE
Imported CSV Not Displaying Updated Meetings in TSML UI

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#134]
Just imported over the latest CSV file from live to staging site under Import & Settings and checked the delete all meetings, locations, groups, districts, and regions option.

Using the plugin front-end, I see the meetings are correct, but it doesn't show up on the TSMl-UI front end. 

Is there a lag time needed for the data to propagate to the UI? I did clear my cache in case it was that reason.

Below are screenshots from same WordPress site showing backend from plugin, front end from plugin and then the UI for the same meeting.

![BB Back End](https://user-images.githubusercontent.com/62247421/122292842-6d718480-cec4-11eb-8054-7a5af0b3830b.png)

![BB Plugin Front](https://user-images.githubusercontent.com/62247421/122292927-80845480-cec4-11eb-9637-121d8f2a743c.png)

![BB UI](https://user-images.githubusercontent.com/62247421/122292950-85e19f00-cec4-11eb-9ec6-c8bc23a90319.png)

**Comment by joshreisner** [comment]
yes, it caches the data in your browser's session cache to save reloading. quit your browser and reopen, or append `?debug=true` to the base URL
