### ISSUE TITLE
Group's Online Meetings Do Not Display Group's In-Person Meetings

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#137]
This may be related to https://github.com/code4recovery/tsml-ui/issues/133

We have a couple of groups holding online and in-person meetings. 

For example, see https://sdi-staging.sussexaa.org/sdi-meetings/?meeting=early-birds-as-bill-sees-it-inside.

There you will see all the meetings held at the physical location (not all of the meetings are part of the group), and all the meetings this group holds online.  I think this is a good display and I like the links to check out these other meetings.

But when you go to any of the online meetings, all that is displayed are the online ones and none of the in-person meetings they are running. Would it be possible to list all the meetings this group is holding, or is that not an easy fix? I realize the plugin only displays number of other meetings (whether they're part of the same group or not) at the physical location only, but this UI is displaying the meeting days and times along with a hyperlink.

![Early Birds In person](https://user-images.githubusercontent.com/62247421/122624572-bfeea480-d06e-11eb-827b-8fd293836b97.png)

![Early Birds online](https://user-images.githubusercontent.com/62247421/122624577-ca10a300-d06e-11eb-8569-5b0699eb27fc.png)

**Comment by joshreisner** [comment]
So here's the logic I said I added:

* If the meeting meets in person, then other in-person meetings at the same location are listed in the location section
* If the meeting meets online and belongs to a group, then other online meetings from that group are listed in the group section

It looks however like it's currently showing the group's online meetings for all meetings. So I guess the first question is do we keep that behavior or make it as originally intended (hide the group online listings from in-person and inactive meetings).

Second, It sounds like you're asking to add in-person meetings in the group section. My concern is that it will mean double-listed meetings (once under location and again under group). This is already happening with hybrid meetings.

Third, what about inactive meetings? They can still belong to the group, and if you click on one you will be seeing this list (if we go with the first point and keep showing group meetings on all meetings).

I'm open to changing the logic. Keep in mind that groups can have meetings at multiple locations, and locations can have meetings from multiple groups or no group.

**Comment by Grateful-Viv** [comment]
> * If the meeting meets in person, then other in-person meetings at the same location are listed in the location section
> * If the meeting meets online and belongs to a group, then other online meetings from that group are listed in the group section

What about adding a third condition?

If the meeting meets online and is part of a group, then all active meetings for that group are listed? 

It would be the reverse of what is shown now when I select a meeting that is in person.

What's confusing with the current way it works is I can see all meetings, whether in-person or online associated with that group, only when viewing the in-person meeting, but not the other way around. 

You do raise some interesting questions and going to have to think on this some more.

Thanks.

**Comment by Grateful-Viv** [comment]
Thought about it some more and I believe if you’re showing meetings for a group under the group section, then it should show all the group’s meetings - not just their online ones. It does it when viewing the in-person meetings and the same should be true when viewing the online ones.  This should only apply to active meetings.

**Comment by joshreisner** [comment]
Ok! I've made the change. This doesn't address the concern about double-listing, but seeing that happening on meetings like this doesn't seem like a big deal: https://react.meetingguide.org/?meeting=ffg-thursday-noon

**Comment by Grateful-Viv** [comment]
> Ok! I've made the change. This doesn't address the concern about double-listing, but seeing that happening on meetings like this doesn't seem like a big deal: https://react.meetingguide.org/?meeting=ffg-thursday-noon

I’m not seeing this change.

**Comment by joshreisner** [comment]
I think this may finally be fixed: https://sdi-staging.sussexaa.org/sdi-meetings/?meeting=early-birds-grapevine

**Comment by Grateful-Viv** [comment]
What I am seeing is for the online meetings, are only the meetings for the group that meets online. None of the in-person meetings are displayed in the group section. See https://sdi-staging.sussexaa.org/sdi-meetings/early-bird-promises.
![Early Birds Promises online](https://user-images.githubusercontent.com/62247421/124120849-3b266200-da42-11eb-86c8-ded90ffacbe6.png)

For meetings that are in-person, it does show all the meetings that meet at the location (including ones that belong to other groups, which is fine), but under the group section, it shows both online and in-person meetings for the group. See https://sdi-staging.sussexaa.org/sdi-meetings/early-bird-promises-inside. 

I think it needs to be consistent. If we're displaying meetings a group has in the group section, then it should list all the meetings for the group whether you're looking at the online instance or the in-person instance. And yes, that would be a double listing for the in-person meetings since it would be also listed in the location section. 

I believe this is the logic you're using:

- If the meeting meets in person, then other in-person meetings at the same location are listed in the location section.
- If the meeting meets online and belongs to a group, then other online meetings from that group are listed in the group section
- If the meeting meets online and is part of a group, then all active meetings for that group are listed in the group section.

I hope this isn't complicating things too much. 

By contrast, the plugin is tied to the location (even if the meeting was online). It would say "xx other meetings at this location" and clicking that then displayed all the meetings. There is no group section either. See https://sussexaa.org/locations/st-marthas-episcopal-church/?tsml-day=5. This of course is a problem when using the same location name for online-only meetings that never met in-person and are using approximate addresses. See #371

**Comment by joshreisner** [comment]
Yes, I'm seeing the in-person meetings listed at the link I shared yesterday: https://sdi-staging.sussexaa.org/sdi-meetings/?meeting=early-birds-grapevine

**Comment by Grateful-Viv** [comment]
That's so bizarre. Been using Chome and made sure it's current with cleared cache. I looked at it then on my iOS device, and I see it there. I also have Chrome, as well as Safari on my phone. Then looked in Firefox on Windows desktop, which is also there.

What's even weirder is the colorful icons to represent phone/online and in-person are black in Chrome. In color using iOS or Firefox.
