### ISSUE TITLE
Type drop down missing label 

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#143]
![1909D53F-760D-4B9B-B498-5117B7D9446B](https://user-images.githubusercontent.com/62247421/124915776-ec3b7800-dfbf-11eb-953e-29a8a56930f5.jpeg)

**Comment by joshreisner** [comment]
Hi Viv, we're having problems with our CDN. It's lagging several days behind the latest release now. Unfortunately it's up to them as to when they issue an update.

We'll be going to a different system in the next release of TSML.

**Comment by Grateful-Viv** [comment]
Thanks for the quick reply.
