### ISSUE TITLE
Include into react application via library

### ISSUE THREAD

**Issue by canewyork** [code4recovery/tsml-ui#145]
Hi - great meeting finder! I'm including into react app and not working too well. Any chance you would create npm library for this?

Thanks!

**Comment by joshreisner** [comment]
Hey this was asked before in #58 and I messed around with it for a while but I couldn't figure it out. If you know how to do it please go ahead and make a PR! Thanks

**Comment by canewyork** [comment]
Sure thing. I did this before. I'll find some time over a weekend and
create a PR.

Thanks for all the service you do!
