### ISSUE TITLE
remove direct google sheets integration

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/tsml-ui#175]
we implemented a direct connection to google sheets at aasanjose.org/meetings for six weeks and got several persistent reports on our helpchat of the meeting finder not working at all. we couldn't reproduce this on a device, so we were not able to identify the cause.

we went back to a JSON feed for two weeks and haven't received any reports.

it seems the google sheets API v4 is not a good public data endpoint.

**Comment by fabform** [comment]
This is handy to find google sheets id
[find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by joshreisner** [comment]
sad to have to remove this feature but it seems the google sheets API is not a great option for content delivery
