### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by altruisticsoftware** [code4recovery/tsml-ui#186]
It'd be nice to get some coverage on these homegrown utils with `jest`.

Maybe like so:
```
src
└─ helpers
   ├── query-string.ts
   └── query-string.spec.ts
```

**Comment by joshreisner** [comment]
yes that would be amazing

**Comment by altruisticsoftware** [comment]
Sweet. I think I'm actually going to pivot to this, don't want to risk the remaining ts migration breaking anything 👍
