### ISSUE TITLE
Speaker / Discussion

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/tsml-ui#217]
i propose that if a meeting is marked as both Speaker and Discussion, that TSML UI translate this into a special type called Speaker/Discussion.

i believe that someone who uses the filter and looks for "Speaker" is expecting to find meetings that are Speaker-only, no discussion

similarly, i believe that "Discussion" should indicate meetings that are discussion-only

i don't think we need to change the JSON spec for this

i would like to have some conversation about this before moving forward

**Comment by leggomyinfo** [comment]
Is there a new tag under the hood that SF/Marin could use instead of passing through Speaker & Discussion individually? Not sure they would want to or if it makes sense to – just curious for now.

**Comment by joshreisner** [comment]
@leggomyinfo not as yet, no. i'll need to check with GSO if they want to add a `Speaker / Discussion` type, but that would not unlock any new benefits to the user
