### ISSUE TITLE
Change the sorting criteria

### ISSUE THREAD

**Issue by leggomyinfo** [code4recovery/tsml-ui#233]
Hi all,

Marcus from SF has reported several complaints about the sorting criteria. It appears that it's day --> time --> all online meetings, and then all in-person meetings --> and I'm not sure what comes after that.

For example, Bernal Big Book has two meetings on Saturdays at 5 pm — named  "Bernal Big Book - Zoom" and "Bernal Big Book - In Person" — but they are not next to each other, as users seem to expect.

I'd like to suggest a sort criteria of day --> time -- > meeting name (not sure what the criteria should be beyond that).

<img width="1280" alt="Screen Shot 2022-06-19 at 12 29 15 PM" src="https://user-images.githubusercontent.com/58055115/174491164-0d7abbe5-e3ec-4910-bbe9-e0b32578f02d.png">
.

**Comment by joshreisner** [comment]
ok 👍
