### ISSUE TITLE
Review "Add to Calendar" event metadata

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/tsml-ui#234]
[received a report](https://github.com/code4recovery/12-step-meeting-list/discussions/834#discussioncomment-2996957) that location metadata is not appearing in outlook

it appears to be working still in ios
![add-to-calendar](https://user-images.githubusercontent.com/1551689/174894339-85023c11-ebe9-49fe-9833-adfced7bce48.png)

**Comment by Studio88-KM** [comment]
Thanks for submitting Josh! Following so I'll know when it's fixed.

**Comment by joshreisner** [comment]
@Studio88-KM try it now? i did a big refactor of this component and it's working great on mac desktop and ios, but i havent been able to test yet on android or windows.

* address is all on one line now
* conference URL links are using the special "Video Call" option
* group websites now use the URL field if present
* on desktop browsers it downloads as a proper `.ics` file

**Comment by joshreisner** [comment]
try this URL so we know we're testing the same thing: https://tsml-ui.code4recovery.org/tests/aasanjose.html?meeting=cup-of-coffee-group-6

when i do it on desktop i get this:
![desktop](https://user-images.githubusercontent.com/1551689/175571397-28220279-218b-48c9-a820-2f7880a9231b.png)

and on mobile:
![mobile](https://user-images.githubusercontent.com/1551689/175571434-b3814a91-ddc5-4804-b431-b9385f7ddc44.png)

do you still get the same behavior on outlook?

**Comment by Studio88-KM** [comment]
Well shoot. Nope, I'm still getting the same thing. Maybe ask another PC desktop user? 

![image](https://user-images.githubusercontent.com/77176347/175574928-08c71783-e222-4915-be56-21c21bbe29f4.png)

**Comment by joshreisner** [comment]
yes. we'll need to figure out from a PC user what, if anything, needs to be change about the format we're sending to ios / desktop:

```
BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
SUMMARY:Cup of Coffee Group
DTSTART:20220624T160000Z
DTSTART;TZID=/America/Los_Angeles:20220624T090000
DTEND:20220624T170000Z
DTEND;TZID=/America/Los_Angeles:20220624T100000
LOCATION:Alano Club of San Jose\n1122 Fair Ave\, San Jose\, CA 95122\, USA
DESCRIPTION:Meeting ID: 618 624 2512 Password: 241520\n----( Video Call )----\nhttps://zoom.us/j/6186242512\n---===---\n+16699009128\,\,6186242512#\,\,#\,\,241520#\nDial-In: (669) 900-9128 Enter Meeting ID: 618 624 2512# Password: 241520
URL:https://www.alanosj.org
END:VEVENT
END:VCALENDAR
```
marking this ticket as "help wanted"

**Comment by StudioLisa** [comment]
Question - so ALL meetings when examined in Outlook running on a Windows platform are failing to take that location and URL data ...or is it a case of some are and some aren't? I'm not real clear on this but I'm interested in helping on this one.

**Comment by Studio88-KM** [comment]
Yes, on my laptop, all emails

**Comment by Studio88-KM** [comment]
Sorry, just updated my comment to include all the information you asked for

**Comment by StudioLisa** [comment]
They just issued an update ('just'... as in like 2 days ago maybe). Always pays to double check too... Never before tried attaching a file to these comments but supposedly it is possible. We shall see... Anyway, it's worth updating or at least double-checking... I know at least 1 bug reporting as fixed now suggests it may be related...

Latest version of Outlook 365 is: Version 2206 (Build 15330.20196)

<img width="579" alt="Screen Shot 2022-07-01 at 4 22 49 PM" src="https://user-images.githubusercontent.com/20824483/176977242-cb13b6f0-0bed-4540-bc99-cc46dbe950b5.png">

**Comment by StudioLisa** [comment]
Something to try... taking the CSV file and getting rid of any TRAILING SPACE in the headers of the columns of data that are not being accepted by Outlook 365. I would also clean the trailing spaces on the whole column. Maybe worth a try at least? Maybe the Apple platforms are just less picky about trailing spaces? Kind of worth a try???

**Comment by Studio88-KM** [comment]
Thanks. Good thoughts.
I do have the latest Outlook.
Trailing spaces. Doesn't look like the headers have trailing spaces but do you have an article that explains how to do it so I can make sure? I've never checked for that.

**Comment by Studio88-KM** [comment]
Can you check if you have a PC? https://wordpress-772911-2627160.cloudwaysapps.com/index.php/meetings/

**Comment by StudioLisa** [comment]
Hey folks, FYI: I checked out the CSV file raw code. In the raw, all data in the 'address' field has quotes at beginning and end of the string (before the comma delimiter) and here and there in other not really logical parts of the file. Wondering if this might be throwing Outlook? I stripped them from this very small test CSV file. Would be great if someone could see if that makes any difference (I don't have anything Windows right now - sorry)

[meetings-LOCATION-TEST-NoQuotes.csv](https://github.com/code4recovery/tsml-ui/files/9033903/meetings-LOCATION-TEST-NoQuotes.csv)
.

**Comment by joshreisner** [comment]
@StudioLisa i think there might be a miscommunication, the "add to calendar" button produces a `.ics` calendar file, not a `.csv` spreadsheet file.

**Comment by Studio88-KM** [comment]
That works! Lisa, can you tell me exactly what you did to make this work? I don't see any quotes or any kind of anything except the actual text/copy in the CSV file so not sure what to change or even how to see the quotes.

Josh, she was referring to the original CSV file :).

**Comment by joshreisner** [comment]
i'm so confused. @Studio88-KM you said the meetings on aasanjose.org were not working for you in outlook, so i don't see how your import has any bearing?

**Comment by Studio88-KM** [comment]
That's a good point! I'm not sure.....I'll find the link to that site and check again.

**Comment by joshreisner** [comment]
try this one, since this is what we were testing before: https://tsml-ui.code4recovery.org/tests/aasanjose.html?meeting=cup-of-coffee-group-6

**Comment by Studio88-KM** [comment]
Now it's working. I don't get it at all. You saw my screenshot when I tested it before. I didn't update Outlook or anything. Very confused why it wasn't working. I'm going to try importing the original CSV file to see if it was in fact my machine. Hold one sec.

**Comment by Studio88-KM** [comment]
I don't get it. Now the original CSV file is working. I am getting data filled in on the Outlook ics.

![image](https://user-images.githubusercontent.com/77176347/177049730-b1b8ceac-4bb4-487f-b0ba-8e3364c09562.png)

**Comment by joshreisner** [comment]
marvelous. i made a change to the code yesterday morning to fix the time zone support, i didn't think to bring it up because the time was loading for you in outlook. but i'm guessing that must have fixed it.

anyway thanks to you and to @StudioLisa , so glad to be able to close this issue.

**Comment by StudioLisa** [comment]
❤️❤️❤️❤️❤️❤️❤️So glad to hear! 

So that means, Josh or whoever, possibly a need to clean (or improve any data cleaning that happens before) of location data before actually letting it populate that.

Am gonna try to look at this later - maybe I can take a stab at this (thank god for the commit process as I would def want someone to check before pulling into the repo!)

L

**Comment by Studio88-KM** [comment]
Thanks so much, Josh, for the excellent support!!! 
And thank you Lisa for your help! 
Lisa, I didn't understand what you were asking on your last comment: "possibly a need to clean (or improve any data cleaning that happens before) of location data before actually letting it populate that.
Am gonna try to look at this later - maybe I can take a stab at this"

**Comment by StudioLisa** [comment]
Unlikely any group would do what I did as I took the file into a raw code editor et al to look at all and any INVISIBLE code in that data and clearly saw those extra/unnecessary “ characters that were being generated by Outlook specifically in those problematic fields (yes, there’s a reason but irrelevant here - it’s an old way of delimiting data that MS has not entirely removed…)

You could, though, use whatever ‘Find and Replace’ feature in Excel, Numbers, or Sheets to search for whatever the ASCII code is for “ symbol (double-quotes) and do a ‘delete all’ on them. 

L


:iPhn

**Comment by Studio88-KM** [comment]
Thanks. I don't see any ASCII code or quotes, though, when looking. I did look for anything extra pretty diligently. Are you saying there's a way to do a search on ASCII to find the quotes or code (not seen by human eye)?

**Comment by Studio88-KM** [comment]
I'm having another issue with the Add to Calendar buttons and Outlook. 

When I click any "Add to Calendar" links on the site, the time on the calendar shows up one hour later (e.g., if meeting is at 8:00 - 9:00 AM EDT, it shows up on the calendar as 9:00 - 10:00 AM EST). I'm using Outlook 365 desktop app on a PC. It's EDT on the meeting and EST on the calendar which I believe are the same. 

Here's a [video](https://www.loom.com/share/9fad4be8d9b245ddb29f5e581a002630) showing the issue. 

Thanks in advance!

**Comment by joshreisner** [comment]
hm! EST is not Eastern Standard, EDT is Eastern Daylight. EDT is correct until 11/6

does this work for you properly in other environments, eg iOS or Android? 

i don't have outlook but on aasanjose.org/meetings the times are correct for me when i add to calendar https://aasanjose.org/meetings?meeting=wednesday-winners shows up at 8:30.

<img width="313" alt="Screen Shot 2022-10-19 at 8 33 48 AM" src="https://user-images.githubusercontent.com/1551689/196737517-938c68b9-2a66-4e0c-88c6-cc930406cb38.png">

could there be an outlook setting that needs to be fixed? it's strange because i'd expect it to share settings with the browser.

**Comment by Studio88-KM** [comment]
I didn't know there was a difference. I looked it up and still don't get it. I guess it's DST? I didn't know they DST had more names. 

I believe it does work for me properly in other environments. I go to a lot of webinars and trainings, etc and constantly "add to calendar" and it works fine. 

I've never seen this before. 

And ah, it's doing the same thing for me on the site you listed above. EST should be 3 hours ahead but when I click the Add to Calendar it's adding 4. So, for a 8:30 AM meeting PST, on my EST Outlook it's popping up with starting time at 12:30 EST.

**Comment by StudioLisa** [comment]
Suggestion for troubleshooting time related issues involving Microsoft anything such as this:

Check that the current time your computer is showing is correct and assure adjustments such as for Daylight Savings Time are setup properly in MS Office itself.

Good luck with all this.

LR










:p

**Comment by Studio88-KM** [comment]
Thanks Lisa! Yes, current time is correct that I can see. Not sure how to assure DST is setup properly but it always changes automatically and works. Any other suggestions? Curious if you tried to see if it's working for you on the example Josh gave above?

**Comment by StudioLisa** [comment]
I don’t have a Windows platforms to do any of that kind of testing so…

I might try messing with Microsoft Office or Outlook’s preference settings for handling time data it pulls from the hardware at least as a workaround.

🤷‍♀️
LR




:iPhn

**Comment by joshreisner** [comment]
i'll ask in our slack to see if anyone has outlook and can try it.

in the meantime, @Studio88-KM could you try from another device like a mobile device?

also, i wonder if the time is actually wrong in real time or not. if you were to add it to your calendar as EST wouldn't that end up at the right time in your system?

here is how you check your timezone in outlook: https://support.microsoft.com/en-us/office/add-remove-or-change-time-zones-5ab3e10e-5a6c-46af-ab48-156fedf70c04 -- apparently the setting is per-calendar, not systemwide
