### ISSUE TITLE
Configuration helper link on main project page is broken

### ISSUE THREAD

**Issue by enderv** [code4recovery/tsml-ui#239]
Not sure if this the best place to report this but on the docs on https://code4recovery.github.io/projects
![image](https://user-images.githubusercontent.com/3226709/182499714-a49d568f-6911-44e7-bbbd-eeba0503d7d1.png)
The configuration helper links return errors like `Not Found - Request ID: 01G9GJ34Q7825T1TJQZN84Q4ET`

**Comment by joshreisner** [comment]
ah, thanks. that page is out of date, i've taken it down now.

for help getting started, please see https://tsml-ui.code4recovery.org/

for advanced configuration, please see https://github.com/code4recovery/tsml-ui#readme
