### ISSUE TITLE
Controls overlapping the table

### ISSUE THREAD

**Issue by enderv** [code4recovery/tsml-ui#250]
Not sure how to label a version but this is just using the latest https://tsml-ui.code4recovery.org/app.js
Noticed it  testing some stuff on my cell phone but was able to repo in chrome by taking the window width the minimum it would let me.
![image](https://user-images.githubusercontent.com/3226709/189011293-8569eeee-64cd-475b-8a60-938c3b65698e.png)

**Comment by joshreisner** [comment]
interesting. i don't see it happening on our demo site
<img width="376" alt="Screen Shot 2022-09-07 at 6 21 31 PM" src="https://user-images.githubusercontent.com/1551689/189012659-4a079717-a434-437b-9737-668803a34bde.png">

could you share a URL where you see it happening? sounds like it could be a CSS conflict

**Comment by enderv** [comment]
Don't have it hosted publicly just using a local file to test things out?
```

<html>
  <div
  id="tsml-ui"
  data-src="https://sheets.code4recovery.org/storage/1Q3k4z0DW-mjPD5V8qauKIjspGv-ukCWup9d7Uev68y8.json"
  data-mapbox="...map-key"
  data-timezone="America/Chicago"
></div>
<script src="https://tsml-ui.code4recovery.org/app.js" async></script>
</html>
```

**Comment by joshreisner** [comment]
interesting. i recommend adding a doctype and a meta viewport tag. looks like bootstrap needs the doctype to render the button properly

```
<!DOCTYPE html>
<html>
  <head>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
  </head>
  <div
    id="tsml-ui"
    data-src="https://sheets.code4recovery.org/storage/1Q3k4z0DW-mjPD5V8qauKIjspGv-ukCWup9d7Uev68y8.json"
    data-mapbox="...map-key"
    data-timezone="America/Chicago"
  ></div>
  <script src="https://tsml-ui.code4recovery.org/app.js" async></script>
</html>
```

**Comment by enderv** [comment]
thanks yep this works! spoke in slack but just to note here if this thread found looks like recent changes make at least the DOCTYPE required now.
