### ISSUE TITLE
Feedback form

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/tsml-ui#252]
we have a stale branch for this: https://github.com/code4recovery/tsml-ui/tree/jr/feedback-form

in addition to the enhanced form, we may want to create a param to hook into TSML's email transport so that it's server-generated rather than client-generated

**Comment by joshreisner** [comment]
we have a stale PR for this: https://github.com/code4recovery/tsml-ui/pull/256 with i will re-sync with `main`, however i'm not 💯 sure this should move forward. 

we recently [improved TSML's feedback_url capabilities](https://github.com/code4recovery/12-step-meeting-list/pull/1031) so groups may now link to a form plugin like gravity forms with all the fields filled out like enhanced feedback. this keeps the email logic and security out of TSML (which is where it would likely have to go, since React doesn't have email access natively)

**Comment by kiyote33** [comment]
I'd like to see a demo on this. I quickly tried to get the feedback_url working in TSML with no joy. Maybe we could include that in our next meeting just so we are all on the same page. It may be we just need to improve documentation or do a How-To video so end-users aren't left in the lurch.

**Comment by joshreisner** [comment]
@kiyote33 sure here is a demo of where things stand now: https://deploy-preview-256--tsml-ui.netlify.app/tests/aasanjose.html?meeting=amor-y-tolerancia-2 - this netlify preview has an annoying bar at the bottom of the screen

we can set up a gravity forms demo on code4recovery.org - we do have some instructions here: https://wordpress.org/plugins/12-step-meeting-list/#can%20i%20set%20a%20custom%20%22update%20meeting%20info%22%20button%20in%20tsml%20ui%3F - this can been an opportunity to confirm they work

we are planning to discuss this in our meeting on the 28th

**Comment by kiyote33** [comment]
Thanks Josh, I’ll dive into today.

 

I am just starting to refocus on C4R today after a gruelling 3 months building the new intergroup site for edmontonaa.org. Thanks for picking up the slack for me in the meantime.

 

Regards…

Wayne

**Comment by joshreisner** [comment]
closing this issue - not going to move forward. a frontend javascript project does not seem like a good place for a feedback form - that's better for some system that has access to the backend, like [central](https://github.com/code4recovery/central/)
