### ISSUE TITLE
Non-Weekly Meetings

### ISSUE THREAD

**Issue by ManFromNapa** [code4recovery/tsml-ui#257]
I'm working to set up TSML, and plan to use a Google Sheet as the backend data source.  We have some meetings that occur on a monthly basis.  It looks like all meetings repeat weekly by default.  Is there a way to list monthly meetings?

**Comment by tim-rohrer** [comment]
No there isn't, as far as I know even with TSML-UI.

In 99% of the cases, monthly meetings are usually in place of a regular weekly meeting but with a different format (i.e., a birthday meeting on the last Saturday of the month). In these cases, we recommend describing that in the meeting notes.

**Comment by joshreisner** [comment]
That's right! We recommend using a different page on your site to list meetings that really only meet once a month.

Meeting Guide also does not support monthly meetings.

**Comment by ManFromNapa** [comment]
Thanks!
