### ISSUE TITLE
Prettier as a dev dependency 

### ISSUE THREAD

**Issue by enderv** [code4recovery/tsml-ui#261]
According to the [Prettier docs](https://prettier.io/docs/en/install.html)  looks like it can be installed as dev dependency and run on demand. See about setting up and updating the contributing docs saying to run before submitting changes.

**Comment by joshreisner** [comment]
i wonder if the prettier github action might also work? that way, if i'm reading this right, people could have whatever they want locally, but it fixes it when the branch is pushed? https://github.com/marketplace/actions/prettier-action

**Comment by enderv** [comment]
Yep looks like that action would do it and would be super handy
