### ISSUE TITLE
Phone Meetings Appear as inactive

### ISSUE THREAD

**Issue by robanonservice** [code4recovery/tsml-ui#291]
Hello, some of our phone meetings appear in active and we do not know why. [Here's](https://www.nycalanon.org/meeting-directory.html) where our plugin is running.

[This is an example](https://www.nycalanon.org/meeting-directory.html?search=Brooklyn+Original+AFG) of inactive phone meetings and not working as expected.

[This is an example](https://www.nycalanon.org/meeting-directory.html?search=Hope+and+Serenity+for+Siblings+of+Alcoholics) of a phone meeting that is currently working.

Attached please find a spread sheet which serves as our meeting feed. The first row represents a meeting that currently works -- the Hope and Serenity for Siblings of Alcoholics.

The rows underneath Hope and Serenity for Siblings of Alcoholics (row 2) represent phone meetings that the plugin on our website is showing as inactive. 

Do you know what we are doing incorrectly for those phone meetings that are showing up as inactive?

[phone problem - Sheet1.csv](https://github.com/code4recovery/spec/files/10769745/phone.problem.-.Sheet1.csv)

**Comment by joshreisner** [comment]
ok should be fixed now. if i refresh https://www.nycalanon.org/meeting-directory.html?meeting=brooklyn-original-mon i see it is no longer inactive. thanks for the feedback!

FYI when you are formatting these, you may improve the link experience with these instructions: https://meetingguide.helpdocs.io/article/ydtd6y1ohn-how-to-add-online-meeting-information#google_sheet_or_custom_databases (i realize you're al-anon but the instructions are still valid for the web meeting finder)

**Comment by robanonservice** [comment]
thank you so much @joshreisner !

By the way, is there anyway for users of [tsml](https://github.com/code4recovery/tsml-ui) to use it at a particular version instead of always loading the latest code?

**Comment by joshreisner** [comment]
yes. we only support the latest version, but technically you can reference a specific static version using the syntax `https://cdn.jsdelivr.net/gh/code4recovery/tsml-ui@1.5.6/public/app.js` (check out our [releases](https://github.com/code4recovery/tsml-ui/releases))
