### ISSUE TITLE
How to add "Alateen" as a type to a meeting?

### ISSUE THREAD

**Issue by robanonservice** [code4recovery/tsml-ui#303]
Hello, 

How does one set a meeting with the type, Alateen?

I see that [this site](https://westchesterputnamalanon.org/meetings/ ) that uses the plugin has an alateen meeting (please see screen shots).

In [the spec](https://github.com/code4recovery/spec#meeting-types), I see a "Concurrent with Alateen" type but not one that is called, Alateen

![Screenshot 2023-03-27 at 8 04 24 PM](https://user-images.githubusercontent.com/117321064/228093454-9d346a27-e839-4f3c-965e-f3e5e7570f73.png)
![Screenshot 2023-03-27 at 8 04 36 PM](https://user-images.githubusercontent.com/117321064/228093480-f841f0c6-51a7-4519-aab3-ec2361828bb2.png)

Thank you for considering my question

**Comment by joshreisner** [comment]
hi @robanonservice are you using the 12 step meeting list plugin as well? if so, you can add a custom meeting type this way: https://wordpress.org/plugins/12-step-meeting-list/#my%20meeting%20type%20isn%27t%20listed%21

**Comment by robanonservice** [comment]
Hi @joshreisner thank you for your reply. [Our site](https://www.nycalanon.org/meeting-directory.html) is not on wordpress. I suppose we are out of luck then when it comes to adding custom types.

**Comment by joshreisner** [comment]
@robanonservice you can still do it, it's just a different method: https://github.com/code4recovery/tsml-ui#add-custom-types
