### ISSUE TITLE
Wix site not showing Mapbox map

### ISSUE THREAD

**Issue by onemooresam** [code4recovery/tsml-ui#314]
Please pardon the second ask for help on this wix mess. Mapbox is not showing on meeting detail pages at https://www.aanc24.org/tsml-test. Wix apparently has their own Mapbox element and I wonder if that's why the TSML-UI implementation isn't working. Any suggestions?

**Comment by onemooresam** [comment]
Thank you, Josh. They're feeding Meeting Guide with that spreadsheet. Since we're doing all this work, should it be converted to the format in the "sample Google Sheet" at the bottom of the TSML-UI page (https://tsml-ui.code4recovery.org/)? (of course, adding the coordinates)

**Comment by joshreisner** [comment]
if you want to add me to the sheet i can try it but i think this might work? `=COORDS(JOIN(", ", F2:I2))`
