### ISSUE TITLE
We (General Service Board of Eating Disorders Anonymous) were using your TSML UI plugin but as of today, meeting listings only display the first 10 matches for any filters

### ISSUE THREAD

**Issue by AnnetteEDA** [code4recovery/tsml-ui#316]
We (General Service Board of Eating Disorders Anonymous - www.4EDA.org) were using your TSML UI plugin but as of today, meeting listings only display the first 10 matches for any filters. We've reverted to using the Legacy UI mode, which resolved the issue. 
Are there any settings in WordPress that we need to adjust to display page numbers, or can we set the default page size to a large number?  Not sure how to set the default page size. 
Thank you very much for any help you can provide. We really like the TSML UI and would much prefer to use it if we can. 
Best regards, 
Annette H 
General Service Board of EDA volunteer

**Comment by joshreisner** [comment]
hi annette, the meeting finder does show 10 meetings at a time, and when you scroll to the bottom, shows the next 10. did something maybe change recently, such as a plugin or theme?

i'm not seeing this issue on other sites, such as aasanjose.org/meetings - it would be great to recreate the problem to figure out what's going on. i loaded your data on a demo page here: https://tsml-ui.code4recovery.org/tests/eda.html do you see the issue there?

if not perhaps you could create a new page on your site and add the `[tsml_ui]` shortcode to see if we could reproduce it there?

**Comment by AnnetteEDA** [comment]
Hi Josh, thanks so much!  I am not seeing the issue on your demo page -- thanks so much for doing that! We might have updated themes recently. One of our webmasters is on vacation, but I will run your suggestion to create a new page outside the menu system with TSML past our other webmaster.

**Comment by miljoe63** [comment]
Hi Josh. I'm working with Annette on this issue. I've created a demo page with the shortcode. We do still see the issue there (https://eatingdisordersanonymous.org/test-meetings-page/). I can also share that we started noticing this issue on July 9 and does not appear that we updated any plug-ins or themes right before or after then. Hope this helps!

Thank you for your time and attention to this. We do love this plug-in, as do the people we support. 

Brigitte
General Service Board of EDA volunteer

**Comment by joshreisner** [comment]
Hi @miljoe63 ! Thanks for the demo, very helpful. looks like something called "avia" has a CSS rule it is applying called `overflow-x: hidden;` which is interfering with the infinite scroll. overriding this appears to fix it. try adding this custom CSS:

```
html.responsive, .responsive body { overflow-x: inherit !important; }
```

![Screenshot 2023-07-13 at 9 53 23 AM](https://github.com/code4recovery/tsml-ui/assets/1551689/0f682a44-5f6f-48d7-aa45-1b680946564b)

**Comment by miljoe63** [comment]
You are wonderful! That was the issue and your fix is perfect. Thank you!! Really appreciate all of your support. 

Brigitte + Annette
