### ISSUE TITLE
Request Option to "Switch to Districts"

### ISSUE THREAD

**Issue by mathteacher** [code4recovery/tsml-ui#317]
The Legacy UI for the 12-Step-Meeting-List WP plugin allowed you to select "Switch to Districts" under the drop down that lets you choose the City/Region. The Puget Sound Central Service Office, Snohomish County Central Office, and Area 72 would all like to request this feature be added to the TSML UI when time allows. Thank you!

**Comment by joshreisner** [comment]
this has come up before: https://github.com/code4recovery/tsml-ui/issues/125

you can use TSML UI now to show district lists by bookmarking searches, and you can make your own site navigation that links to those searches, eg

* District 01 -> /meetings?search=district+01
* District 02 -> /meetings?search=district+02

TSML UI will make use of the `district` index in your JSON or google sheet for searching so you don't need to add district to notes

but i don't want to bring back the "switch to districts" button in the Anywhere menu - i want to maintain the app's focus on being a tool to serve new AA members who are looking for a recovery meeting
