### ISSUE TITLE
Meetings not displaying in visitor's timezone

### ISSUE THREAD

**Issue by jeznag** [code4recovery/tsml-ui#318]
Thanks heaps for the hard work on tsml-ui. It looks perfect for our use case (an Australia wide meeting list for DA).

I saw that https://github.com/code4recovery/tsml-ui/issues/93 was closed but it doesn't seem to work the way I'd expect.

I've configured tsml-ui to use Sydney time but it still shows Perth meetings in Perth time.

![CleanShot 2023-07-20 at 19 01 06](https://github.com/code4recovery/tsml-ui/assets/1034890/ac093bd9-2072-4624-b2f5-61ddc9f6e158)

If I click on the Perth meeting, it shows both timezones but in a confusing way. No-one in Australia would understand what GMT+8 vs GMT+10 means.

![CleanShot 2023-07-20 at 19 01 40](https://github.com/code4recovery/tsml-ui/assets/1034890/cdec1edc-7d25-48ac-ae1b-36e1a5b627cf)

Steps to replicate:

```
<div id="tsml-ui" data-src="https://sheets.code4recovery.org/storage/1YRpUph8Xfw-hX-2IegFx_S4YQUprFTqLPYxfL42Pb98.json" data-mapbox="pk.eyJ1IjoiZGFhdXNpbnRlcmdyb3VwIiwiYSI6ImNsaTVvc2VicjFpYmszcm8wbXp0ZmFpcnIifQ.Jo3HdrcE5_r0EBU-DiTP1Q" data-timezone="Australia/Sydney"></div>
```

Here is my spreadsheet: https://docs.google.com/spreadsheets/d/1YRpUph8Xfw-hX-2IegFx_S4YQUprFTqLPYxfL42Pb98/edit#gid=0

**Comment by joshreisner** [comment]
oops yes there was a bug here when `data-timezone` is specified - it was not normalizing other timezones to that zone. i would still remove `data-timezone` for your use-case but the bug should be fixed now
