### ISSUE TITLE
conference_url and conference_phone no longer accepted as Google Sheet column headers

### ISSUE THREAD

**Issue by mathteacher** [code4recovery/tsml-ui#319]
The Puget Sound Central Service meeting list (https://meetings.pugetsoundaa.org/) has been successfully using TSML UI for about a year, but sometime recently all of our online meetings stopped showing up in the meeting list. I just figured out that if I change the column header "conference_url" to "Conference URL" and the column header "conference_phone" to "Conference Phone" that it again would show our online meetings.

If possible, could Code for Recovery please have the TSML UI once again accept "conference_url" and "conference_phone" as column headers in a Google Sheet. Changing the column headers as mentioned above fixed the situation with our TSML UI meeting list but broke one of our other web apps that also utilizes our Google Sheet data. Considering that "conference_url" and "conference_phone" are the specified labels in the Meeting Guide Spec to me it makes sense that they would be valid options for Google Sheet headers in TSML UI.

Here is our actual Google Sheet with the column headers changed so that it currently works for Online Meetings:

https://docs.google.com/spreadsheets/d/13W4lBuRWKpnHNOC_3wTXI5anLVOkyvMmyn4Wvqx1z3c/edit?usp=sharing

Here is a copy of our Google Sheet with the original column headers that no longer works for Online Meetings:

https://docs.google.com/spreadsheets/d/1o54yYx2hEM_F94ac63Q4ohN8Erfy1-K5gib9lnf0a3o/edit?usp=sharing

**Comment by joshreisner** [comment]
hm, looks like a recent refactor no longer slugified `mountain_view` to `mountain-view` which caused it not to recognize your snake_cased column names

i don't know that this is inconsistent -- the [sample sheet](https://docs.google.com/spreadsheets/d/1iA8oVtddHVEZ8gslWPlTrfBfbgJpiS0Tt6sFOTi_5dk/edit#gid=687617754) that we and GSO link to has always used spaces in the column names

i've changed it back on our end but you'd probably be safer adopting the suggested column names
