### ISSUE TITLE
Make meeting active without url that matches our recognized formats

### ISSUE THREAD

**Issue by tiptop96** [code4recovery/tsml-ui#324]
We have meetings that are based around emails and one based around a website. These are listed as `inactive` which is not what we want. Examples can be found here https://meetingfinderstorage.z13.web.core.windows.net/meetings-osa.html

I played around with setting `online = true` and `active = true` in the API response but as I expected the logic described in the docs seem to take precedence.

Is there a way for us to solve this?

**Comment by joshreisner** [comment]
yes, you could add more “custom” conference providers, here is an example of how we do that in one of our tests: 

https://github.com/code4recovery/tsml-ui/blob/bbdc4441754d320a66f1151c7465884297ccd73a/public/tests/aasfmarin.html#L29

you will need a matching conference_url for each meeting, so you may need to make something up for the email meeting

but if you’re always going to be listing only online meetings then perhaps our online meeting list project would be a better fit: https://github.com/code4recovery/online-meeting-list it supports the concept of “ongoing” meetings and doesn’t require a location

**Comment by tiptop96** [comment]
Ahh cool, thanks!

That sounds like a good option as well. What does it mean that it supports ongoing meetings?

**Comment by joshreisner** [comment]
not much. you had some fake times in your list for these meetings. if you take then out (you should), then TSML UI will label them  “Appointment“ meetings, whereas Online Meeting List would use the term “Ongoing”

you could change the term TSML UI uses in your configuration

**Comment by tiptop96** [comment]
Oh cool! Yeah we should remove that. Then I understand a bit better. Thanks as always for helping out! ❤️
