### ISSUE TITLE
Search option defaults to "Near Location" for some users

### ISSUE THREAD

**Issue by jeznag** [code4recovery/tsml-ui#328]
Thanks heaps for building tsml-ui. It's working great for the DA Australian website

However, I've had a few people report that they can't see certain meetings on our list. After checking further it seems it's defaulting to near location.
![CleanShot 2023-09-05 at 20 39 56](https://github.com/code4recovery/tsml-ui/assets/1034890/29e325f5-95dd-496b-81b6-be6eda590364)

**Comment by joshreisner** [comment]
hi @jeznag something must be getting lost in  translation, could you please include more details? perhaps describe the correspondence that you had with a user?

the search in your screenshot above is not near location. what does it show or not show?

**Comment by jeznag** [comment]
Sorry that was the wrong screenshot. In Near Location, only some meetings appear

![CleanShot 2023-09-07 at 18 55 12](https://github.com/code4recovery/tsml-ui/assets/1034890/93852ba9-c05e-4a23-bcf7-01eff3ce6ed8)

vs Search mode

![CleanShot 2023-09-07 at 18 55 42](https://github.com/code4recovery/tsml-ui/assets/1034890/a564d0c9-b5db-4834-a5b6-8c65eb280552)


I'd like to actually disable the Near Location option and only show search as almost all of our meetings are online only.

People seem to be getting the Near Location filter without purposefully selecting it.

**Comment by joshreisner** [comment]
ok thanks - that's right that only geographic meetings show as options when "near location" mode is enabled, which i think makes sense.

the only way to get into that mode without clicking on it is to visit the link - https://www.debtorsanonymous.org.au/?mode=location - perhaps some users have it bookmarked? 

there's currently not a setting to remove the option from TSML UI - you could try adding some javascript to the page to remove `mode=location` from the URL if present when coming from a bookmark:

```html
<script>
  var url = new URL(window.location.href);
  if (url.searchParams.get('mode')) {
    url.searchParams.delete('mode');
    window.history.replaceState({}, '', url);
  }
</script>
```

**Comment by jeznag** [comment]
Thanks I've added that in.

One thing that confuses me is that some of the zoom meetings are showing up as in person meetings and some are not even though they have the same kind of location data. Meeting list is at https://debtorsanonymous.org.au/

![CleanShot 2023-09-09 at 20 26 51](https://github.com/code4recovery/tsml-ui/assets/1034890/376722d4-4aff-417b-99c2-a37a95e65a1c)

![CleanShot 2023-09-09 at 20 27 30](https://github.com/code4recovery/tsml-ui/assets/1034890/ca8067c5-6f97-4ee3-a01d-31e774308da2)

vs

![CleanShot 2023-09-09 at 20 29 05](https://github.com/code4recovery/tsml-ui/assets/1034890/a5beae5d-8a92-42fc-9d4a-6ab7d543d460)

![CleanShot 2023-09-09 at 20 29 20](https://github.com/code4recovery/tsml-ui/assets/1034890/10a79ab0-e689-4ff2-838c-43775fc3821f)

Source google sheet: https://docs.google.com/spreadsheets/d/1YRpUph8Xfw-hX-2IegFx_S4YQUprFTqLPYxfL42Pb98/edit#gid=0

**Comment by joshreisner** [comment]
@jeznag yeah it can be confusing, especially with google sheets because there isn't built-in feedback ui to show you what's going on

the `location` column in your sheet is a the name of the place, often this is a building name, or could be "Online" - but it has no impact in terms of wehther

in your case TSML UI is looking at your `coordinates` column to decide if the meeting is at a specific address or not. (it can use other signals, but since you have that column that's what it prefers). in-person meetings should have a single comma (lat,lng) vs online meetings that have three commas (lat,lng,lat,lng) which should describe a rectangle
