### ISSUE TITLE
Help with the sunspot WP Theme 

### ISSUE THREAD

**Issue by thepripri** [code4recovery/tsml-ui#329]
![Screenshot of Website](https://github.com/code4recovery/tsml-ui/assets/81442297/40ea9b22-e8bb-4fa8-a16a-01aa6f5915cb)

**Comment by joshreisner** [comment]
thanks @thepripri! i'm working on some enhancements as part of #287 that should help with this - i'll update here when they can be demoed

**Comment by joshreisner** [comment]
hey @thepripri i've got a PR ready, but need to do some extensive testing before releasing. when you get a chance, could you update your page code to:

```
<div
  id="tsml-ui"
  data-src="https://aavirginia.org/wp-admin/admin-ajax.php?action=meetings&district=district-33-manassas"
  data-mapbox="pk.eyJ1Ijoiam9zaHJlaXNuZXIiLCJhIjoiY2tvYXA0YnZxMGRldDJxbzdta25uNGphdiJ9.eay-UKgIT99ALmdw08xBPw"
  data-timezone="America/New_York"
></div>
<script>var tsml_react_config = { map: { style: 'mapbox://styles/mapbox/dark-v11' } };</script>
<script src="https://deploy-preview-330--tsml-ui.netlify.app/app.js" async></script>
```

then go to WordPress Dashboard > Appearance > Customize > Additional CSS and add this:

```
body.tsml-ui #secondary {
  display: none;
}
body.tsml-ui #content {
  padding: 0;
  margin-top: -26px;
}
body.tsml-ui #content, body.tsml-ui #content > article, body.tsml-ui .entry-content, #tsml-ui {
  min-height: calc(100vh - 24px);
}
body.tsml-ui #content > article > header {
  display: none;
}
body.tsml-ui #main {
	width: 73.7%;
}
body.tsml-ui #primary {
  width: 100%;
}
body.tsml-ui #wrapper {
	max-width: none;
}
body.tsml-ui .entry-content {
	margin: 0
}
#tsml-ui {
	--background: #292625;
	--link: #fcb03e;
	--text: #fff;
	--in-person: #66cc66;
	--online: #6699cc;
	--inactive: #cc6666;
	--font-family: Ubuntu, "Helvetica Neue", Helvetica, Arial, sans-serif;
}
```

hopefully it will look like this:
![list](https://github.com/code4recovery/tsml-ui/assets/1551689/074fbc3f-c764-4fc4-b8aa-0a1cf71a90ac)
![meeting](https://github.com/code4recovery/tsml-ui/assets/1551689/a62f9c12-d3ab-4fbd-8223-b527634e0684)

let me know! thanks
