### ISSUE TITLE
Wheelchair Accessible type is missing in TSML UI

### ISSUE THREAD

**Issue by charlesrbasin** [code4recovery/tsml-ui#335]
Meetings with Wheelchair Accessible type do not show the missing types on the detail page. The edit meeting view shows it has the blue check mark.
https://alanonma.org/meetings/?weekday=sunday&type=online&meeting=25004-monthly-business-meeting-district-4
TSML Version 3.14.22
WP version: 6.3.2
![Edit-Meeting-“25004-Monthly-Business-Meeting-District-4”-‹-MA-Al-Anon-Alateen-—-WordPress](https://github.com/code4recovery/tsml-ui/assets/47933751/1029d57f-3dcc-454d-8c5b-733ec906d92c)
This type is missing in TSML UI version but not in Legacy UI.
similar problem to Discussion #1198?

**Comment by joshreisner** [comment]
hi @charlesrbasin yes, that's right, meetings that don't have a physical location are not considered to be "wheelchair accessible" by TSML UI

here's an example of a meeting with a phyiscal location that shows the Wheelchair Accessible type https://alanonma.org/meetings/?meeting=38035-pause-for-serenity-sunday-am-afg

**Comment by charlesrbasin** [comment]
I restored the address, and it shows Wheelchair Accessible type in the meeting detail, but meeting is not in the list when the Wheelchair Accessible type is selected.
https://alanonma.org/meetings/?search=6160&meeting=6160-constantly-changing-afg
![Edit-Meeting-“6160-Constantly-Changing-AFG”-‹-Test-Development-site-—-WordPress](https://github.com/code4recovery/tsml-ui/assets/47933751/b17ca5e7-4094-4a6c-85ad-84dda20d8e1b)

**Comment by charlesrbasin** [comment]
I restored the address, and it shows Wheelchair Accessible type in the meeting detail, but meeting is not in the list when the Wheelchair Accessible type is selected.
https://alanonma.org/meetings/?search=6160 <https://alanonma.org/meetings/?search=6160&meeting=6160-constantly-changing-afg> &meeting=6160-constantly-changing-afg

 

Barry Nelson

   ***@***.***> ***@***.***

   <https://alanonma.org/> alanonma.org

**Comment by charlesrbasin** [comment]
Legacy UI https://staging7.alanonma.org/meetings/?tsml-day=4&tsml-type=X does show https://staging7.alanonma.org/meetings/6160-constantly-changing-afg/?tsml-day=4&tsml-type=X with type Wheelchair Accessible

TSML UI https://alanonma.org/meetings/?weekday=thursday&type=wheelchair-accessible does NOT show https://alanonma.org/meetings/?search=6160&meeting=6160-constantly-changing-afg

**Comment by joshreisner** [comment]
yes, we should also make it so Wheelchair Access only displays on in-person meetings in TSML, but we haven't done that yet

**Comment by charlesrbasin** [comment]
Your comment confuses me. TSML UI only displays in-person meetings with type Wheelchair Accessible when that type is selected. The Legacy UI displays that type for meetings that are online only.

**Comment by joshreisner** [comment]
hi @charlesrbasin to reframe: we believe that Wheelchair Access is a type that only makes sense to apply to meetings that meet in person, or in-person + online, but not online-only

if i am a user who selects the Wheelchair Access type from the dropdown, i do not want to see an online-only meeting listed there, it doesn't make sense

in AA we have a number of other types that fit this category: Babysitting Available, Breakfast, Candlelight, Child-Friendly, Concurrent with Al-Anon / Alateen, Fragrance Free, Outdoor, Smoking Permitted, Wheelchair-Accessible Bathroom

when TSML UI sees one of these types applied to an online-only meeting it ignores it. this is a feature, not a bug. it's to make the app's behavior more meaningful to users

we are investing more energy in developing features for TSML UI, with the goal of someday (but not soon) deprecating the "Legacy UI" interface. that is why TSML UI has more features that TSML, such as this, but also things like "Add to Calendar" or "Meetings In Progress"

hope that helps clarify a little
