### ISSUE TITLE
Markers are projected into space 😅

### ISSUE THREAD

**Issue by tiptop96** [code4recovery/tsml-ui#338]
After some of the recent updates we are experiencing an issue where markers kinda float on an axis.
![image](https://github.com/code4recovery/tsml-ui/assets/31468763/167f8b31-7fa8-4e91-bbd0-f8c527de0e0f) (from: https://meetingfinderstorage.z13.web.core.windows.net/meetings.html?view=map)
It is especially clear with a global view but is also apparent on a local scale (Swedish meetings hovering over Belarus).
![image](https://github.com/code4recovery/tsml-ui/assets/31468763/af914b02-45ee-42ba-9ad7-5d06179cfc6d) (from: https://en.ca-sweden.se/moten?view=map)
I tried looking through recent changes, read the readme and also I set `map.style` to one of the classic ones but projection remains weird.

Also we are receiving this warning: 
![image](https://github.com/code4recovery/tsml-ui/assets/31468763/9aed6058-b6bc-49da-a34e-58f79021b702)
However after loading the mentioned CSS the issue remains. This might be a separate issue but leaving it here for now.

Any idea what is going on?

**Comment by joshreisner** [comment]
hey i think you're right to look at the map style. in a recent update we bumped it from `mapbox://styles/mapbox/streets-v9` to `mapbox://styles/mapbox/streets-v12` - you should be able to set it back with your `tsml_react_config` variable

or also you might try playing around with the `projection` parameter. From the [docs](https://docs.mapbox.com/mapbox-gl-js/guides/projections/) it says:

> In the [latest Mapbox styles](https://docs.mapbox.com/api/maps/styles/#mapbox-styles), [Globe](https://docs.mapbox.com/mapbox-gl-js/guides/projections/#globe) is the default projection. (Streets, Outdoors, and Satellite Streets v12 and Light/Dark v11)
> In Navigation, Satellite, and earlier style versions the default is [Mercator](https://docs.mapbox.com/mapbox-gl-js/guides/projections/#mercator).

**Comment by joshreisner** [comment]
yah if you extend your `tsml_react_config` with 
```
        map: {
          style: 'mapbox://styles/mapbox/streets-v10',
        },
```

it should go back to normal. i'll see if i can't fix the projection prop, but if i can't, then i'll make this the default soon

<img width="1419" alt="Screenshot 2023-11-03 at 10 30 50 AM" src="https://github.com/code4recovery/tsml-ui/assets/1551689/53c3c7cf-e504-4882-a168-20c6885f96ce">

**Comment by tiptop96** [comment]
Thanks, everything is looking great again! 🥳
