### ISSUE TITLE
aanc24.org was working, now shows meetings as inactive

### ISSUE THREAD

**Issue by onemooresam** [code4recovery/tsml-ui#360]
[aanc24.or](https://www.aanc24.org/meetings) was working properly. Now it is showing meetings as inactive but only on the site, not in the Meeting Guide app. Looking at the spreadsheet template, it looks like it's been updated from what we used. 

The public URL is not validating in the JSON validator: https://docs.google.com/spreadsheets/d/e/2PACX-1vQ-EsPaWBC7zmVHcY1j-tPJPtDAJdvVR_TZrTh_E4KuWPOOJwBPBdDpNwOydO50R6nQL2LXWnR7FN98/pubhtml

Do we need to reformat and run through https://sheets.code4recovery.org/? Running the current spreadsheet (https://docs.google.com/spreadsheets/d/1mi8Ndpt2wAYP0cskn8BUDj9TcwkLLrMFD5Ig9l0-zE0/edit?usp=sharing) through it yields a list of warnings.

**Comment by joshreisner** [comment]
hm, there was an update a few days ago, i wonder if it's related. try adding a country column to your sheet and USA in all the rows, to see if that's a quick fix

**Comment by onemooresam** [comment]
FIXED! Thanks, Josh!
