### ISSUE TITLE
CSS to defend against dropdown going off the screen

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/tsml-ui#362]
for https://github.com/code4recovery/12-step-meeting-list/discussions/1365

#tsml-ui button { white-space: normal; }

also not sure if `right; 0` on last control makes sense - or maybe it should be desktop only

**Comment by ckyoga** [comment]
Thanks Josh.  I will try this out in a bit.

**Comment by joshreisner** [comment]
this fix rolled out with https://github.com/code4recovery/tsml-ui/pull/363
