### ISSUE TITLE
Unexpected Application Error

### ISSUE THREAD

**Issue by bubfcg** [code4recovery/tsml-ui#380]
When using the new tsml ui, I get this error:
Unexpected Application Error!
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Eu (https://tsml-ui.code4recovery.org/app.js?ver=6.5.2:5:60173)
![image](https://github.com/code4recovery/tsml-ui/assets/167124715/bd92d2b6-2896-4ad3-adcd-79c6ebf5bc9b)

**Comment by gkovats** [comment]
Hi @bubfcg , could you give us some details on where this is running? It'd be helpful to run your meetings data through the widget to recreate the issue.

**Comment by bubfcg** [comment]
Hi @gkovats it is running on https://ca-nn.nl/meetings/ but I am using the old interface now. What info do you need from me?

**Comment by gkovats** [comment]
@bubfcg Sorry, could you try enabling the TSML UI meeting display, and then sending over a snapshot of the meetings page HTML? The issue appears to be with the configuration object responsible for offering translations of the UI, I assume to Dutch. Looking at the object would be able to see where it's failing and recreate the issue.

**Comment by bubfcg** [comment]
Sure, see attached textfile for html @gkovats 
[html.txt](https://github.com/code4recovery/tsml-ui/files/15053339/html.txt)

**Comment by bubfcg** [comment]
Hey @gkovats I have translated it. Instead of A.A. I wrote C.A. or Cocaine Anonymous in the file, since that's where I need it for. If that shouldn't be done in this file, please change it ;)
[nl.js.txt](https://github.com/code4recovery/tsml-ui/files/15098352/nl.js.txt)

**Comment by bubfcg** [comment]
Can I upload the file myself somewhere @gkovats ? Or should I wait for an update from your side?

**Comment by joshreisner** [comment]
i've created a PR, @gkovats when you get a chance if you could take a 👀: https://github.com/code4recovery/tsml-ui/pull/384

**Comment by gkovats** [comment]
Thanks @joshreisner, sat on this long enough. Looks good, seeing Dutch on my end.

**Comment by bubfcg** [comment]
> Hey @gkovats I have translated it. Instead of A.A. I wrote C.A. or Cocaine Anonymous in the file, since that's where I need it for. If that shouldn't be done in this file, please change it ;) [nl.js.txt](https://github.com/code4recovery/tsml-ui/files/15098352/nl.js.txt)

@gkovats and @joshreisner as I mentioned before, I have changed A.A. / Alcoholics Anonymous in the Dutch translations for C.A. / Cocaine Anonymous because that's what I need for my website. You can change that if needed.

By the way, if you need any more files translated to Dutch: I'm happy to help ;)

**Comment by gkovats** [comment]
@bubfcg - Dude! If you have time, could you go through these poorly Google translated meeting types? They're obviously not all very CA centric, but anything you add helps.
[types.json.txt](https://github.com/code4recovery/tsml-ui/files/15194786/types.json.txt)
](url)

**Comment by bubfcg** [comment]
@gkovats Sure, I translated everything I knew the Dutch words for we use in our AA and CA meetings in The Netherlands.
[types.json.txt](https://github.com/code4recovery/tsml-ui/files/15195291/types.json.txt)
