### ISSUE TITLE
when searching near a location, the query string doesn't add the search parameter to the url

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/tsml-ui#383]

**Comment by gkovats** [comment]
How do you do this in the app? I filtered on a region / city, added a search term, and url updates with the search string. Is there another way?

**Comment by adminaa87** [comment]
The TSML UI is not working with an URL search like it is on Legasy UI.

This link build with legacy UI: https://meetingsdev.aa87.org/meetings/?tsml-day=5&tsml-distance=5&tsml-mode=location&tsml-query=Montr%C3%A9al%2C%20QC%20H1V%202E2%2C%20Canada

If change it for TSML UI: https://m.aa87.org/meetings/?tsml-day=5&tsml-distance=5&tsml-mode=location&tsml-query=Montr%C3%A9al%2C%20QC%20H1V%202E2%2C%20Canada

The filters are not working.

**Comment by joshreisner** [comment]
@adminaa87 the query parameters are different in TSML UI. 

instead of 
```
tsml-day=5&tsml-distance=5&tsml-mode=location&tsml-query=Montr%C3%A9al%2C%20QC%20H1V%202E2%2C%20Canada
```

you want
```
weekday=friday&distance=5&mode=location&search=Montr%C3%A9al%2C%20QC%20H1V%202E2%2C%20Canada
```

https://m.aa87.org/meetings/?weekday=friday&distance=5&mode=location&search=Montr%C3%A9al%2C%20QC%20H1V%202E2%2C%20Canada

**Comment by adminaa87** [comment]
Problem fixed.
Thank you.
