### ISSUE TITLE
Map Terrain Missing - Only showing red pin

### ISSUE THREAD

**Issue by hellotait** [code4recovery/tsml-ui#399]
Although I see the red pin location marker, I don’t see the actual map terrain on my meeting pages. I’ve checked to ensure the MapBox Token is updated and active, and it is. Please assist me.

The page I need help with: [Problem Page](https://coloradocma.org/meetings/?meeting=life-after-crystal-friday)

**Comment by joshreisner** [comment]
is it possible you've fixed it already? this is what i see at the link:

<img width="1840" alt="Screenshot 2024-07-05 at 4 21 36 PM" src="https://github.com/code4recovery/tsml-ui/assets/1551689/f1bec464-8bec-4b26-af06-9fe688407a3e">

**Comment by hellotait** [comment]
Okay, it's working on Safari! That's great!! However, Chrome is not functioning, even after I adjusted permissions and cleared the cookies. Here is what it looks like on Chrome on my iMac Desktop.
![Image 7-5-24 at 5 28 PM](https://github.com/code4recovery/tsml-ui/assets/152348438/5a878ab2-bf18-402b-a310-02fa96ed9fb0)

**Comment by joshreisner** [comment]
<img width="1840" alt="Screenshot 2024-07-05 at 4 36 54 PM" src="https://github.com/code4recovery/tsml-ui/assets/1551689/c5316c59-cd28-4071-a1eb-f4758178dfda">

looks good to me in chrome! maybe check the javascript console? i see that you're logged in to WP - maybe try in incognito to see if there's a difference there, or maybe a chrome extension is interfering for some reason?

**Comment by joshreisner** [comment]
oops never mind i thought you were logged in - probably still worth trying incognito though, because usually that turns off extensions as well

**Comment by hellotait** [comment]
Josh, thank you for your help. I cleared the js cache and it works perfectly. THIS WAS A LOCAL ISSUE. Take care!  ~Tait
