### ISSUE TITLE
dropdowns shouldn't be taller than the viewport

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/tsml-ui#404]
perhaps have a maxHeight and scroll internally? this is an issue with the Anywhere dropdown on aastl.org/meetings mentioned in https://github.com/code4recovery/pdf/discussions/73#discussioncomment-10317493

**Comment by gkovats** [comment]
![image](https://github.com/user-attachments/assets/9c7d5890-7a3c-4595-a00a-b7063b023ebb)

```
max-height: 50vh;
overflow-y: auto;
```
Not the prettiest, but seems to work?

**Comment by joshreisner** [comment]
yah! maybe a little bigger even, like 80vh? whatever feels right

**Comment by joshreisner** [comment]
we should test it on mobile as well, might be weird there if it scrolls in two places
