### ISSUE TITLE
Filter's duplicate when using `filters[]` in config

### ISSUE THREAD

**Issue by KalobTaulien** [code4recovery/tsml-ui#406]
Here's the preview of what it looks like without any config settings:
![image](https://github.com/user-attachments/assets/f0097f10-f8c4-4b74-be4e-d024afa1751e)

When I add the following config:
```js
var tsml_react_config = {
    filters: ['region', 'distance', 'weekday', 'time', 'type'],
}
```
It duplicates the filters. 
![image](https://github.com/user-attachments/assets/6b5de734-5679-4316-b224-54b0811b4edd)

The original goal was to remove one filter by providing the list of filters we wanted to keep.

**Comment by joshreisner** [comment]
@KalobTaulien i think i solved this hopefully - take a look a lmk, thanks!
