### ISSUE TITLE
The app give the round arrow turning around with nothing....

### ISSUE THREAD

**Issue by Totoquebec** [code4recovery/tsml-ui#410]
On Android.

If my GPS is of (has alway) then the app didn't see it and cannot find a meeting near me the it roll and roll...

That logic but it should warn me that my GPS (Localization) is off

and/or

Give me just the full list

and/or 

give me the list with a choice of country/city/Area
![Screenshot_20240910_214819_CA Meeting Finder](https://github.com/user-attachments/assets/e077adfc-10d4-4c1f-9f3f-160158a14009)

**Comment by joshreisner** [comment]
thanks @enderv - going to close this issue since it seems like this could be more about the CA app implementation, but please reopen if you see a bug in location handling more generally

**Comment by Totoquebec** [comment]
Oups Sorry...
