### ISSUE TITLE
Pushing dev site to production and meeting single path not updating

### ISSUE THREAD

**Issue by bish73** [code4recovery/tsml-ui#424]
Just launched a new site for https://www.aadallas.org/ and when you try to click into an individual meeting it still uses the dev server file path. I can't figure out where or how to update this. 

https://www.aadallas.org/meetings/

Please advise...

**Comment by joshreisner** [comment]
hi @bish73 we have found that this is usually fixed by going to one of your meetings on the live site and saving changes, then refreshing the list, let us know if that doesn't fix it!

**Comment by bish73** [comment]
FYI switching the tsml theme back and forth from legacy UI to TSML and back to Legacy seems to have snapped it out of it...
