### ISSUE TITLE
Hybrid meetings: add address?

### ISSUE THREAD

**Issue by FlipperPA** [code4recovery/tsml-ui#67]
If we display the location address above the `Conference URL` / `Conference Phone` buttons, I think we'll have all we need for hybrid meetings, plus the indicator that the location is temp closed if strikethrough is present.

Want me to take a hack at this?

**Comment by joshreisner** [comment]
So we'd then be showing the address twice in the left column and once on the map? I'm not sure if this is needed.

I just made a commit which added the strikethrough to the addresses, if you could pull from that and maybe mark up a screenshot with what you're thinking that'll help me visualize it.

**Comment by FlipperPA** [comment]
Sorry, I meant in the table listing view. A picture is worth a thousand words:

![image](https://user-images.githubusercontent.com/68164/88488902-ae844180-cf5e-11ea-8452-d57b849b29b9.png)

* The first highlighted meeting is `Temp Closed`. I could remove the `Temp Closed` flag if we show the address above the `Zoom` / `Phone` buttons with strikethrough like the other addresses.
* The second highlighted meeting is a hybrid. The address is being shown anywhere in the table listing view.

I guess this goes back to the conversations we were having about hybrid meetings. It now occurs to me that we often won't know whether the meeting is hybrid in-person/online meeting, or two separate meetings. I'm also not sure if it matters, as long as we can get the drunk where they're going? What do you think?

**Comment by joshreisner** [comment]
I think if a meeting is `Temp Closed` but meeting online, then adding the address in just to cross it out seems bad.

The only problem is that if you see the buttons then you kind of wonder if the meeting is also happening in person or not. I'm not sure if I have a good fix for that, although I think jamming the address in there would create problems visually.

I don't love that the city, district, and GSO number are all jammed in with the location. My goal is to have a lighter reading experience in this view. 

All that said, I don't think that this online / in person problem is fully solved yet, and would like to have a conversation with a UI designer about this.

It occurs to me that the camera / phone button text could be removed, allowing an address to fit next to it, but this is an anti-pattern for accessibility.

Perhaps a type (and flag) for 'hybrid' is the least-bad option available? I am reluctant to admit this because I don't think people actually go out _looking_ for hybrid meetings but this might be the least-bad way to convey that you can go either route (in person or online).

**Comment by joshreisner** [comment]
Perhaps we don't need a type in the spec for this, perhaps, like with online meetings, it can get applied automatically?

**Comment by FlipperPA** [comment]
I'm thinking we can probably do something automatically. I agree with you that this problem isn't just fully solved... but not fully realized yet. Things have been in such flux for the past few months, I think we're still pretty far from knowing what patterns / best-practices will naturally emerge across the fellowship over the next few months / years. I've been doing a lot of thinking about your comment about where we'll be in five years, and I think you're right. Now that Pandora's Box has been open, I agree that the popularity of online meetings as an option for busy schedules will not recede in popularity even post-vaccine.

I'm not a fan of the District / GSO number at all! I'm pushing to only have it on the meeting detail screen. It was voted to be put there to match the print guide, but I think over the past year, I've made a solid case to have it removed. Now that we have a UX engineer on the tech committee, I have an ally. :) We'll be discussing it a week from Wednesday at our monthly tech committee meeting.

**Comment by joshreisner** [comment]
Lois had another idea for this, which is to add a directions button, so the button group here is potentially Zoom / Phone / Directions. This would have the effect of indicating which meetings are meeting in person

**Comment by joshreisner** [comment]
I can take a crack at this if you want. There have been a few changes in the default view and I don't think Philadelphia has been negatively affected, but original problem you stated is definitely still an issue. Here's what the app looks like now with new-ish Philadelphia data, as you can see, hybrid meetings still need an address:

![list-buttons](https://user-images.githubusercontent.com/1551689/120002627-e21e6680-bf89-11eb-8fb7-4b4e3c663728.png)

The default view handles this with a green address label:

![default](https://user-images.githubusercontent.com/1551689/120003103-47725780-bf8a-11eb-8a1e-80745d095ad8.png)

Couple options here, let me know which you prefer:

1. i could try to add address above the buttons for hybrid meetings
2. you could switch to the default view as is and we could eliminate `listButtons`
3. `listButtons` could have the appearance of the default view but the labels (zoom, phone, and potentially address) are clickable

Lmk your preference

**Comment by FlipperPA** [comment]
@joshreisner I really like the look of the default view (with green/red/blue buttons). Option 3 sounds great: if we could make it just so the buttons are clickable for `listButtons`, that would rock. Hopefully, that'd simplify the code a bit. Let me know what you think, and thanks!

**Comment by joshreisner** [comment]
Ok sounds good. I'll make that change so we can close the issue. 

Eventually I would like to explore ways to remove all customizations, but that's more of a long-term vision.
