### ISSUE TITLE
A11y Improvements

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/tsml-ui#70]
Make sure the user experience is good using a screen reader.

**Comment by FlipperPA** [comment]
Have you ever done testing with Safari's voice over? It's a humbling experience we do for Wagtail.

**Comment by joshreisner** [comment]
turns out we have a really good accessibility score in lighthouse right now (98) with the only issue being "Background and foreground colors do not have a sufficient contrast ratio." That makes sense, there are a lot of grays.

That said, I'm going to close this issue until I hear more specific issues reported. We do have aria-labels on our Selects, and titles on our main CTA buttons.
