### ISSUE TITLE
Change label for default location filter

### ISSUE THREAD

**Issue by leggomyinfo** [code4recovery/tsml-ui#78]
We've received a significant amount of feedback that the "Everywhere" filter is confusing for users. They expect to see all meetings there, not just in-person meetings (which includes hybrid). We've addressed this in our [meeting finder FAQ](https://aasfmarin.org/meetings) but I think there may also be a (hopefully) small fix with a meaningful UX pay-off: change the label from "Everywhere" to "Any location". This does two things:

1. It makes it clearer what this filter is for.
2. It harmonizes the label with that of the other filters.

Small reconciliation with https://github.com/code4recovery/react/issues/77#issuecomment-716935348: I reference the label of "Cities" there; "Locations" is probably better since it's more generic and I assume Intergroups are treating regions/sub-regions differently.

Thoughts?

**Comment by leggomyinfo** [comment]
We've realized that absent a significant redesign of TSML, we need to accept that our users associate online meetings with physical locations. In order to keep our data clean and manageable, we have added an extra field on our Meetings table: TSML_remote_meeting_neighborhood. (We already had a field for TSML_remote_meeting_county so that the approximate location for online meetings required by Meeting Guide would reflect the county where the meeting started since a lot of folks from Marin meetings were frustrated that it showed "San Francisco".)

region and subregion are populated in the following order:

- if the meeting is attached to a physical location (in Airtable terms: a record on the Meetings table is attached to a record on the Locations table), region and subregion will inherit the city and neighborhood (in the case of San Francisco) or "Marin" and the city (if the location is not in SF).
- if the meeting is not attached to a physical location, it then is populated by TSML_remote_meeting_county and TSML_remote_meeting_neighborhood, both of which are fields on the Meetings table.
- if we lack either, it will not be counted in the location dropdown — this only applies to meetings which started post-COVID and have always been exclusively online.

This is better than our original solve which was to have a "Remote" region. This didn't work well primarily because hybrid meetings could only be in the Remote, SF, or Marin region (which was a very confusing UX).

I still think changing the label to "Anywhere" is a small improvement to harmonize the labels (all the rest start with "Any") but regardless the dropdown is now functioning the way folks expect it too.

**Comment by FlipperPA** [comment]
Hey @leggomyinfo - this can be configured during initialization to be any string you'd like:

https://github.com/code4recovery/react/blob/master/src/i18n/en.js#L34

```javascript
var tsml_react_config = {
  strings: {
    en: {
      region_any: 'Any Location'
    },
  },
};
```


I think I'd prefer `Any Location` as well, but is setting this in the configuration good enough?

**Comment by joshreisner** [comment]
seeing as i'm making changes today, i went with "Anywhere" -- it seems like a better fit since a) it's shorter and b) `Location` is used elsewhere to mean a meeting location, rather than a regional geographic area.
