### ISSUE TITLE
tsml_react_config is not defined

### ISSUE THREAD

**Issue by brianw-area24** [code4recovery/tsml-ui#81]
After out meeting on Saturday, I tried the new tsml_ui (react) using my district's feed. When I first did that, when I followed the instructions under "Install on my website", I didn't see any meetings. After a little troubleshooting, I found the error "tsml_react_config is not defined" in the Web Console of my browser.

I then had to add the following code to my web page:
`<script>
    var tsml_react_config = {
        };
</script>`

Of course I could add options to this code if I wanted to.

I'm seeing the same thing when I click on the second "Here's a demo" link (https://react.meetingguide.org/demo.html), in that it give the same tsml_react_config is not defined error.

Brian W.

**Comment by FlipperPA** [comment]
Ah, hmmm... it looks like we might need to initialize this as an empty struct if it isn't passed. Thanks for the heads up, @brianw-area24.

**Comment by FlipperPA** [comment]
This problem is here: https://github.com/code4recovery/tsml-ui/blob/master/src/helpers/settings.js#L38

```javascript
flags: tsml_react_config?.flags ? [] : ['Men', 'Women'],
```

A straightforward solution would seem to be doing this before the settings struct:

```javascript
// Initialize tsml_react_config if it isn't defined in HTML
if (typeof tsml_react_config === 'undefined') {
  var tsml_react_config = {};
}
```

However, this overwrite the `tsml_react_config` that is sent in from HTML. Will have to investigate further. I have a solid repro, at least.

**Comment by jackieoh1** [comment]
> This problem is here: https://github.com/code4recovery/tsml-ui/blob/master/src/helpers/settings.js#L38
> 
> ```js
> flags: tsml_react_config?.flags ? [] : ['Men', 'Women'],
> ```
> 
> A straightforward solution would seem to be doing this before the settings struct:
> 
> ```js
> // Initialize tsml_react_config if it isn't defined in HTML
> if (typeof tsml_react_config === 'undefined') {
>   var tsml_react_config = {};
> }
> ```
> 
> However, this overwrite the `tsml_react_config` that is sent in from HTML. Will have to investigate further. I have a solid repro, at least.

Hi FlipperPA - where would I put this code exactly?   Thank you...

**Comment by joshreisner** [comment]
@FlipperPA yeah this is a head scratcher. how do you check for the existence of this variable without overwriting it locally? i tried your idea in `settings.js` and it did just that.

If fixed the demo so at last that should be working. The only people encountering this should be the people who don't follow the instructions and choose not to define that variable. Anyone using WordPress should have that defined with the time zone at least.

**Comment by FlipperPA** [comment]
@joshreisner Yeah, maybe we just make the variable mandatory. I'm okay with that, at least for now!
