### ISSUE TITLE
Add config for start offset

### ISSUE THREAD

**Issue by 97eighty** [code4recovery/tsml-ui#83]
Create a config variable to store the 10 minute offset used to sort meetings. The default is hard coded as -10 minutes but a user might want to increase this to 60 or 90 minutes to leave meetings in view until after the end time.

Hard value is stored in data.js on line 407

```javascript

      //if time is earlier than 10 minutes ago, increment diff by a week
      if (meeting.minutes_now < -10) {
        meeting.minutes_now += 10080;
      }

```

**Comment by joshreisner** [comment]
sounds good. you can set that time with

```
<script>
  var tsml_react_config = {
    now_offset: -30,
  };
</script>
```
