### ISSUE TITLE
Google Sheets Styled demo not working

### ISSUE THREAD

**Issue by blafving** [code4recovery/tsml-ui#87]
Solving this issue will help us figure out whether our integration with Google Sheets will still work.

The [styled demo](https://react.meetingguide.org/demo.html) mentioned in the README is not working due to: Uncaught ReferenceError: tsml_react_config is not defined

Try creating an instance of tsml_react_config before meetings src with
            <script>
            var tsml_react_config = {};
            </script>

I had additional trouble with Google Drive after this debug on my test site, and i will continue to look at that. I will share further info as I learn more if this doesn't do the trick.

Thank you!

**Comment by joshreisner** [comment]
Should be working again now! Thanks for letting us know that was out of date. https://react.meetingguide.org/demo.html
