### ISSUE TITLE
TSMLui and TSML v4.0 Questions/Comments

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#91]
I'm using the TSML Plugin and have opened a page on my staging site using the [tsml_react] shortcode. 

When editing meetings, I still would need to go through the backend? The way I've been doing it is not through the WP dashboard, but through the link address: https://sussexaa.org/meetings/ and then going to the meeting and then selecting edit meeting.  I see that the shortcode method only will let me edit the page which is not what I want to do when I select the meeting.

The meeting listed through TSML React does not show the district number or have last date updated listed. It also does not include a place for people to request a change to the listing. Will this be added in updated versions?

I am using the widgets for the TSML plugin. Specifically, custom HTML for Meeting Top where I have a lot of information to convey, and Meeting Detail Bottom where I have more custom HTML. I like these options, and hope this will be available on the front end in future rollouts.

I have a number of sub menus so people can quickly find meetings that have reopened, for example. Using the word "opened" anywhere in the meeting info (be it in the meeting notes or location notes is enough for the TSML plugin search bar on the meeting list to find every meeting where there is an instance of the word. How then can I make a link like I've done on my live site to return all "opened" meetings and add it to the menu bar or anywhere on a page that I'd like?  Here is the link in the example I just gave: https://sussexaa.org/meetings/?tsml-day=any&tsml-query=opened

It would be helpful to have suspended (TC) meetings crossed & greyed out with red letters stating location temporarily closed, online meetings with the green lettering "online". There needs to be a space or forward slash when designating "women" or "men" (and that should be green like the plugin is). 

There needs to be a space in the meeting list page between time and day of week.

Otherwise, I like a lot of how the front end looks and thank you for working on this.

**Comment by FlipperPA** [comment]
Hi @Grateful-Viv, thanks so much for giving it a try! I'm roping in @tech2serve, who can answer your WordPress specific questions better than me.

This front-end pulls from the same API feed that the app does. The TSML WordPress Plugin creates that API feed. So it is my understanding that you will need to use the WordPress meeting and location editor to make changes.

I've just pushed a bug fix which was causing some issues on the meeting detail view, which shows the district numbers on my version of the site, but we're also a Django site rather than WordPress: https://www.AASEPIA.org/

The color choices were an intentional choice, and can be overridden with a stylesheet. We should probably add an example of how to do that in the README.

**Comment by tech2serve** [comment]
> I'm using the TSML Plugin and have opened a page on my staging site using the [tsml_react] shortcode.

This is great feedback. Thank you! Some answers below.

> 
> When editing meetings, I still would need to go through the backend? The way I've been doing it is not through the WP dashboard, but through the link address: https://sussexaa.org/meetings/ and then going to the meeting and then selecting edit meeting. I see that the shortcode method only will let me edit the page which is not what I want to do when I select the meeting.

The approach you've been using works because you're logged into the site. Frankly, I'm not sure this approach could still be made to work cleanly, but we can keep the need in mind and see if there is a simple option.

Regardless, you will still be able to edit meetings through the backend.
> 
> The meeting listed through TSML React does not show the district number or have last date updated listed. It also does not include a place for people to request a change to the listing. Will this be added in updated versions?

Let me start by saying we want to call this new capability TSMLui and leave "React" out of it. React is the technology being used. We're still cleaning up references to this.

I'm not following your statements about district numbers or date updated. Are you talking about on the single meeting page?

Our goal will be to bring most all features over from the current Wordpress front end
> 
> I am using the widgets for the TSML plugin. Specifically, custom HTML for Meeting Top where I have a lot of information to convey, and Meeting Detail Bottom where I have more custom HTML. I like these options, and hope this will be available on the front end in future rollouts.

The widget for TSML itself should be completely separate. We'll need to investigate how it/they interact(s) with TSMLui.
> 
> I have a number of sub menus so people can quickly find meetings that have reopened, for example. Using the word "opened" anywhere in the meeting info (be it in the meeting notes or location notes is enough for the TSML plugin search bar on the meeting list to find every meeting where there is an instance of the word. How then can I make a link like I've done on my live site to return all "opened" meetings and add it to the menu bar or anywhere on a page that I'd like? Here is the link in the example I just gave: https://sussexaa.org/meetings/?tsml-day=any&tsml-query=opened

I'll need to research this further, but will again state now that our goal is that TSMLui will provide more capabilities than the current front end. 
> 
> It would be helpful to have suspended (TC) meetings crossed & greyed out with red letters stating location temporarily closed, online meetings with the green lettering "online". There needs to be a space or forward slash when designating "women" or "men" (and that should be green like the plugin is).
> 
> There needs to be a space in the meeting list page between time and day of week.
> 
> Otherwise, I like a lot of how the front end looks and thank you for working on this.

**Comment by Grateful-Viv** [comment]
Hi @FlipperPA FlipperPA thanks for responding. I've seen your site ever since it was demoed at NAATW last fall. Very nice, indeed.

I noticed on your site, as opposed to the my WP site using the TSMLui that inactive meetings have the location address crossed out, as well as showing the type after the meeting name. That is currently not the case in what I am seeing on my staging site.

One of my pet peeves that I will put in a request for is that temp closed type is tied to temp location, even if the meeting is online. I wish there could be active or inactive status available, so that the meeting list is not cluttered with meetings that aren't actually meeting. 

> The color choices were an intentional choice, and can be overridden with a stylesheet. We should probably add an example of how to do that in the README.

I can do CSS anywhere on my site and hope this is what you mean.

Thanks.

**Comment by Grateful-Viv** [comment]
> > When editing meetings, I still would need to go through the backend? The way I've been doing it is not through the WP dashboard, but through the link address: https://sussexaa.org/meetings/ and then going to the meeting and then selecting edit meeting. I see that the shortcode method only will let me edit the page which is not what I want to do when I select the meeting.
> 
> The approach you've been using works because you're logged into the site. Frankly, I'm not sure this approach could still be made to work cleanly, but we can keep the need in mind and see if there is a simple option.
> 

I hope you can do this because the WP dashboard for searching through meetings is a kluge. Though I can sort by day or time, or region or date published -- it is cumbersome to go through as opposed to looking at the list in the WP plugin front end.
>Regardless, you will still be able to edit meetings through the backend.
Say this isn't so!! :(
> 
> > The meeting listed through TSML React does not show the district number or have last date updated listed. It also does not include a place for people to request a change to the listing. Will this be added in updated versions?
> 
> Let me start by saying we want to call this new capability TSMLui and leave "React" out of it. React is the technology being used. We're still cleaning up references to this.
> 
> I'm not following your statements about district numbers or date updated. Are you talking about on the single meeting page?
Yes, on a single meeting page. I am hoping we can capture the same information: Group, District, last date updated, and the form (though limited) for folks to request an update to the listing,

> 
> Our goal will be to bring most all features over from the current Wordpress front end
that would be most excellent.

> > I am using the widgets for the TSML plugin. Specifically, custom HTML for Meeting Top where I have a lot of information to convey, and Meeting Detail Bottom where I have more custom HTML. I like these options, and hope this will be available on the front end in future rollouts.
> 
> The widget for TSML itself should be completely separate. We'll need to investigate how it/they interact(s) with TSMLui.

I know I can edit the top of the page before the shortcode, as well as the bottom, but having the Meeting Detail Top or Bottom widgets was very handy and hope it carries over.
> 
> > I have a number of sub menus so people can quickly find meetings that have reopened, for example. Using the word "opened" anywhere in the meeting info (be it in the meeting notes or location notes is enough for the TSML plugin search bar on the meeting list to find every meeting where there is an instance of the word. How then can I make a link like I've done on my live site to return all "opened" meetings and add it to the menu bar or anywhere on a page that I'd like? Here is the link in the example I just gave: https://sussexaa.org/meetings/?tsml-day=any&tsml-query=opened
> 
> I'll need to research this further, but will again state now that our goal is that TSMLui will provide more capabilities than the current front end.

More capabilities! awesome.
> 
> > It would be helpful to have suspended (TC) meetings crossed & greyed out with red letters stating location temporarily closed, online meetings with the green lettering "online". There needs to be a space or forward slash when designating "women" or "men" (and that should be green like the plugin is).
> > There needs to be a space in the meeting list page between time and day of week.
> > Otherwise, I like a lot of how the front end looks and thank you for working on this.

You didn't comment on this. There needs to be a space between the time and day of the week on the meeting list page. I see that it's that way on the live site for AA/SF.

Also, may I assume the colors, as @FlipperPA indicated, can be controlled by CSS styling on my end? The red temp closed, and green online, for example were very fast visuals. 

Thanks!

**Comment by joshreisner** [comment]
This is a big conversational thread, sort of hard to make progress on without breaking it up. I think I see six issues. 

I believe this one is already fixed:

1. spacing between elements in the list

These three issues pertain to WordPress specifically and would need a WordPress specific solution in the TSML plugin. If you want the team to address these my recommendation would be to [create separate TSML issues](https://github.com/code4recovery/12-step-meeting-list/issues) for these:

2. editing meeting link
3. widgets
4. request a change form

These two relate to this project, I will create separate issues for these and link them here:

5. display district, group, and last updated info on meeting detail page if present
6. table view TC meetings grayed out, ensure ability to style type "flags" (eg Online Meeting etc)
